.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE, CODE_OF_CONDUCT.md
No linked issue
Adds code of conduct, issue templates, pull request templates and CODEOWNER files.
Note: I filled this pull request by manually copying the pull request template :) If you try to edit the pull request description, you see all the comments.
I am trying to implement the missing bits of the [Community Standards](https://github.com/AcademySoftwareFoundation/OpenRV/community) checklist.
N/A
Please watchout for typos. I am known for injecting them everywhere I go.
=> Code of conduct, issue templates, pull request template and codeowners

doc/build_system/config_linux_centos7.md
https://github.com/AcademySoftwareFoundation/OpenRV/discussions/60
Fixes an issue repoted by [@rubikstriangle](https://github.com/rubikstriangle) and resolved by [tjjackson](https://github.com/tjjackson) where the ncurse-devel is not properly defined.
The right package name is ncurses-devel, as defined [here](https://centos.pkgs.org/7/centos-x86_64/ncurses-devel-5.9-14.20130511.el7_4.x86_64.rpm.html)
Typo.
Linux
N/A
N/A
=> Fix typo in Linux documentation

src/build/make_pyside.py
Building on the Mac OS update from last week fails the build.  The reason for this is that the clang headers used in building pyside are too old and not compatible with the latest Mac SDK.  There are pages and pages full of compilation errors when attempting to compile pyside.
To fix it, we will detect the version of clang on Mac and download the headers matching that version, even though this is not the version recommended by PySide, we don't have much choice.
Fixing the build
Tested on Mac OS 13.3. and CentOS7.
=> Fix building on MacOS >= 13.3

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp
Fix corruption when playing media with inserts [SG-29243]
A studio provided us with a ProRes media clip that played back fine in RV until it reached the middle section where it showed corruption for the last half of the video. 
QuickTime Player on Mac was able to playback the same clip without corruption. 
Note that RV decodes this ProRes video clip using FFmpeg + AppleProRes decoding lib. 
The issue here is exclusively caused by the FFmpeg wrapper used in RV: src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp 
The video corruption is caused by something we had never had to deal with before in RV: a change of native video pixel format within the same video track. In this particular clip, the native video format changes from yuv422p16le to uyvy422 at about the middle section of the clip. This broke …
=> Fix corruption when playing media with inserts

src/plugins/rv-packages/otio_reader/otio_reader.py
This branch fixes two issues and is brought over from the commercial RV branch:
- Global image bounds on import
- Blend order
Previously, we would just use the first clip's image bounds to set the global bounds (ie canvas size) which works fine if all clips have the same bounds.  However, if not, anything outside of the first clip's bounds will be clipped. To fix this, we'll simply calculate the union of all bounds and use that as the canvas size. The canvas will initially still be framed around the first clip, but with this fix zooming out ensures the image outside of those bounds will be displayed.
The blend order in a stack, for some reason (I assume legacy), is not actually a stack.  The first input is displayed on top instead of the last. To fix this, set the …
=> OTIO Import: Fix blend order and global bounds

src/lib/app/mu_rvui/help_mode.mu
User's Manual and Reference Manual updated to link to the Read the Docs URLs.
=> Update RV manual links

cmake/dependencies/python3.cmake, cmake/macros/rv_stage.cmake
- Added a new config variable for the _python3_executable.
- Changed file handling logic
- Updated zip command to store files without directory structure
- The new config variable ensures consistent use throughout the code
- There is a check for an arg_Files variable which determines which files are used
- Zip command will now includes all files without the directory structure
- Added the RV_DEPS_PYTHON3_EXECUTABLE var to the python3.cmake file
- Added a check for arg_files variable in rv_stage.cmake file
- Changed zip command from -J to -j
=> Changed Cmake files

cmake/macros/rv_stage.cmake, src/lib/app/RvPackage/PackageManager.cpp, src/lib/app/RvPackage/RvPackage/PackageManager.h
Reverts AcademySoftwareFoundation/OpenRV#183
Signed-off-by: shannonyearwood <syearwood1059@gmail.com>
=> Revert "Add Support for Directories in RV Packages SupportPath"

src/lib/app/mu_rvui/inspector.mu
The color inspector will now receive a 'graph-state-change' event whenever the pixel color mode changes (the event already existed, it was just about binding it). We use that event to trigger the correct code inside the inspector.mu to update the inspector.
I also found another bug while working on this one, about the average color pixel; instead of taking the pixel color from the current mode, it would take the source pixel color no matter what.
Also fixed some janky inspector resetting event.
When in Final Color mode in the Color Inspector, a change in the graph would not always update the inspector. You'd need to move the inspector manually to update it.
Mac 
- inspector.mu
1. Download [color_inspector_bug.rv.zip](https://github.com/AcademySoftwareFoundation/OpenRV/files/11772217/color_ …
=> [BUG] Fix the color inspector final color mode

cmake/globals/rv_git.cmake
Added the 'CACHE STRING' flag to the RV_GIT_COMMIT_SHORT_HASH and RV_GIT_BRANCH cmake variables to expose them in RV Commercial.
We want the correct commit info for the about box (although would only be shown on a dev build)
MacOS, should be good on other OS though.
- Making sure the CMakeCache is OK.
N.B.: might need to delete and recreate the CMakeCache.
=> Added hash and branch to cache

README.md, cmake/dependencies/python3.cmake
N/A
Updates Python to 3.10.x
Be compliant with the VFX Reference platform.
Tested on all platform before merging.
N/A
N/A
=> Update Python to 3.10.x for VFX Reference Platform 2023

src/plugins/rv-packages/otio_reader/otio_writer.py
[ 214: Fix OTIO Export with nested sequences ]
Fixes #214 
This branch fixes exporting nested sequences to OTIO.  The problem was with the kwargs parameters to `create_otio_from_rv_node` which dispatches the call to a function for each supported node type.  The method to parse a track was setting parameters that only applied to the `create_item` function so if there was any other node type (in this case a second sequence) the call would fail.
To fix it, I simply just use the values from args/kwargs directly, instead of mixing args with positional aruments and kwargs with named arguments. This way both functions in the map have the same signature so they can be called with the same parameters.
I noticed the same problematic pattern in a few other methods as well, so I clean it up …
=> Fix nested sequence OTIO export

cmake/dependencies/ffmpeg.cmake, cmake/dependencies/openssl.cmake
This reverts commit d960e3dc3504728a3734f3e5bc831dc36c04aee0.
=> Revert "Fix Windows FFMpeg build error (#235)"

docs/rv-manuals/rv-mu-programming.md, docs/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-four.md
Some minor Python/Mu doc changes
=> Minor Python/Mu doc changes

cmake/macros/rv_stage.cmake
N/A
When rebuilding a rvpkg, clear the rvinstall file so the builds know that the rvpkg install step is dirty.
I lost time expecting the newly built rvpkg content to be automatically added to the staged app.
I tested it on MacOSX, but it's not platform-specific.
N/A
N/A
=> Automatically install rebuilt packages

cmake/dependencies/python3.cmake
N/A
Fixing the build since OCIO looks for python3.9
The build is broken
Windows, Mac & Linux
- Refactoring the code to avoid code duplication and sync'ing the short number with all other version numbers in this file
=> VFX 2023: Updating Python short version number

cmake/dependencies/oiio.cmake, cmake/macros/rv_stage.cmake, src/lib/base/TwkUtil/FileLogger.cpp, src/lib/base/TwkUtil/TwkUtil/FileLogger.h, src/lib/ip/OCIONodes/OCIOIPNode.cpp
N/A
Merge Upstream/main
OIIO SHA/Hash changed and is breaking all the builds.
None, safe merge and once in the vfx2023 branch, I will use the Build Machines to ensure the build is good.
- OIIO hash fix
- Merge main to this branch: minimal number of commits.
=> Vfx2023: sync upstream/main for oiio hash fix

src/lib/app/RvCommon/RvConsoleWindow.cpp, src/lib/base/TwkUtil/FileLogger.cpp, src/lib/base/TwkUtil/TwkUtil/FileLogger.h
N/A
Reverts a change introduced when we introduced the logger where lines were printed without the newline. Now, we tell SPDLOG to not add an extra EOL character and keep the one that comes from OpenRV's internal.
Callstacks, and other similar wall of texts, were unreadable.
Tested on MacOS, but should not be platform-specific
Reviewing commits per commit is better since the first one is the clang-format one.
N/A
=> Fixes OpenRV outputs

src/lib/app/RvCommon/RvConsoleWindow.cpp
N/A
Fixes the build. I forgot to add changes to #283.
The build is broken.
Build.
N/A
N/A
=> Fixes the build after missing changes

src/lib/ip/IPBaseNodes/FileSourceIPNode.cpp
N/A
1) Avoid submitting cookies and headers parameters to FFMPEG if they are empty strings... it doesn't like it.
`No trailing CRLF found in HTTP header` -> empty header. 
2) Use the proper delimiter of `\r\n` for headers because that's the spec.
There was one warning line per web media loaded. 
Tested on MacOS, but not platform-specific. 
The change is in 44c9bdc3ea77ff1a3dba83b7beeff130a8db624b, the other commit is just automatic formatting from my editor. 
N/A
=> Avoid sending empty headers and cookie to FFMPEG

cmake/dependencies/python3.cmake, src/build/make_pyside.py
N/A
Avoid using Qt's main mirror since it's often really slow and unreliable.
I got the link from https://download.qt.io/static/mirrorlist/
CI and local builds are failing because of the unreliability of the official sources.
Tested on MacOS 
N/A
N/A
=> Download Qt artifacts from the  University of California mirror

src/build/make_python.py
N/A
Reorder RV's PYTHONPATH so stuff bundled with RV comes first. While doing it, removes entries that doesn't exists on disk.
1) It allows RV to not clash with stuff installed in the user site directory. It will grab it's PySide2 or cryptography version before the one from the user site directory. It's a popular problem with RV's usage with compiled python packages.
2) It avoids having to go through the multiple entries that could be slow network paths in the sys.path while looking for any packages.
Tested on MacOS. Building on all platforms. 
N/A
Before: 
```
$ DO_NOT_REORDER_PYTHON_PATH=1 PYTHONPATH=exists-1:fake-1:fake-2:exists-2:fake-3:exists-3:exists-4:exists-5 _build/stage/app/RV.app/Contents/MacOS/py-interp -c 'import sys; print("\n".join(sys.path))' …
```
=> Reorder RV's PYTHONPATH

docs/build_system/build_errors.md, docs/build_system/config_windows.md
N/A
Added extra msys2 packages to install and a note on conflicting system-wide vcpkg.
Minimize future problems when setting up a Windows build machine.
N/A
N/A
N/A
=> Update docs for windows build

src/build/requirements.txt, src/plugins/rv-packages/node_graph_viz/PACKAGE, src/plugins/rv-packages/node_graph_viz/node_graph_viz.py
N/A
Do not build OpenRV with matplotlib and networkx.
These are requirements for a package that is disabled and hidden by default, there are no values in packaging them in OpenRV.
(TBD)
N/A
N/A
=> Do not automatically include Node Graph Viz dependencies

src/plugins/python/gtoContainer/gtoContainer.py
=> Fix typo in gtoContainer.py

CMakeLists.txt, docs/conf.py
n/a
Fix the version and release value in the documentation
same as above
n/a
n/a
=> Fixing version and release value for sphinx

src/lib/ip/IPCore/ShaderFunction.cpp
Fixes #403
Prevent shader collisions with array variables by adding a hash to the array variable name to make it unique.
This was already done for regular variables but not for array variables.
In the scenario describes in Issue #403, the OCIOv2 generated two shaders, one for the OCIOFile node and another one for the OCIODisplay node. RV could not successfully compile the resulting shader because there was a collision name with some OCIOv2 generated global variables. 
**Problem:**
Original OCIOv2 generated shaders:
const int ocio_grading_rgbcurve_knotsOffsets_1[8] = int[8](-1, 0, -1, 0, -1, 0, 0, 15);
...
float ocio_grading_rgbcurve_evalBSplineCurve_1(in int curveIdx, in float x)
const int ocio_grading_rgbcurve_knotsOffsets_1[8] = int[8](-1, 0, -1, 0, -1, 0, 0, 9);
...
float …
=> Fix OCIOv2 error with baked user DisplayViewTransform

.gitignore
Added the default _install/* target directory to the repository's .gitignore.
The _build directories were already ignored, this looks like an oversight?
=> [444: Add _install directory to .gitignore]

cmake/dependencies/aja.cmake
n/a
Follow the same standard as the other *.cmake for dependencies.
Build fails on Windows
=> Fix issue with aja.cmake

.github/workflows/ci.yml, .gitignore, cmake/defaults/rv_targets.cmake, cmake/dependencies/ffmpeg.cmake, docs/build_system/config_macos.md, docs/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-two.md, src/bin/imgtools/rvls/CMakeLists.txt, src/bin/imgtools/rvls/main.cpp, src/build/make_python.py, src/lib/app/RvCommon/RvPreferences.cpp, src/lib/ip/IPBaseNodes/FileSourceIPNode.cpp, src/lib/ip/IPCore/ShaderFunction.cpp, src/plugins/rv-packages/otio_reader/annotation_hook.py
n/a
I rebased by cherry-picking the commits since the last rebase.
Rebase to main to minimize efforts
=> Qt6 Feature branch - Rebase to main

src/build/make_python.py
n/a
Reverting changes that I made to support Python 3.11 for VFX2024. **Those changes were affecting Windows only**.
Reverting the change to make sure that the next release goes smoothly. Currently, I am having a lot of issue with 3.11. I need to work on that separately.
Windows
=> Reverting changes made to make_python.py for VFX2024

CMakeLists.txt
=> Set OpenRV version to 2.2.0

src/plugins/rv-packages/otio_reader/otio_reader.py
NA
To fix the following error when loading OTIO with multiple media representations
'ERROR: Unable to determine aspect ratio…' 
When multiple media representation sources are created, we can only retrieve the media_info of a source if it is the active source. That's because multiple media representation in Open RV is optimized to only load a source when it gets activated.
If the current source is not the active source, we can't get the media_info so we fall back to the active source's media_info as our best guess.
Successfully tested on macOS
=> Prevent 'ERROR: Unable…' when loading OTIO with MMR

src/lib/app/RvCommon/RvDocument.cpp
n/a
I removed old code that was dealing with a potential memory leaks related to QAction and specific behavior for MacOS that causes issues now.
This changes was done to fix an issue where all the menus are duplicated multiple times in the QToolBar.
Rocky 8 and MacOS
=> Feature/qt6 - Fix issue with all menu being duplicated on MacOS

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp, src/lib/ip/IPBaseNodes/SequenceGroupIPNode.cpp, src/lib/ip/IPCore/Session.cpp, src/plugins/rv-packages/otio_reader/annotation_hook.py, src/plugins/rv-packages/otio_reader/effectHook.py, src/plugins/rv-packages/otio_reader/otio_reader.py, src/plugins/rv-packages/otio_reader/paint_schema.py
n/a
Rebasing the feature branch with the main branch
See commits list
=> Feature/Qt6 - Rebase with the main branch

rvcmds.sh
n/a
I added checks to detect existing installations of Qt 5 or Qt 6. The search prioritise Qt 6 over Qt 5. 
Once Qt is found, the script set the right variables for the aliases. 
If QT_HOME is already set, I added a check to detect if it is Qt 5 or Qt 6.
Note that the logic only look for `Qt*` and either `5.15*` or `6.5*` in the path. The script is not looking at the actual libraries files.
rvcmd.sh had to be reworked to support both Qt 5 and Qt 6.
Rocky Linux 8
=> Feature/qt6 - Support both Qt 5 and Qt 6 in rvcmd.sh

src/plugins/rv-packages/rvnuke/rvNetwork.py
n/a
This PR update the rvNetwork,py to Python 3 (copied from src/plugins/python/network/network/rvNetwork.py).
Nuke and RV integration was broken. An image or video could not be played in RV.
Rocky Linux 8
=> Fix network issue with rvnuke plugin

cmake/dependencies/ffmpeg.cmake, src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp
n/a
The rebase only include the PNG changes, but I want to get it right away in the feature/qt6 branch since it is affecting performance.
Rebase
=> Feature/qt6 - rebase to main

README.md, docs/build_system/config_macos.md
NA
This commit updates the the macOS build instructions to reflect main branch: Qt6+VFX CY2024
Build instructions were stale
=> Update mac build doc to reflect main branch: Qt6+VFX CY2024

src/bin/nsapps/RV/main.cpp
When starting RV, Qt complains that qtwebengine won't be able to use opengl acceleration. This is due to macOS having to use OpenGL 2.1 as opposed to a version 3.2-or-later-with-compatibility-profile, since macOS does not support compatibility profiles.  This warning appears in the creation of the QApplication. Unfortunately we install the main message handler after the creation of the QApplication, so I had to install a temporary handler just before creating QApplication. IMO this is a better solution than moving the entire message filter in its own platform-independent file; since this message is platform-dependent anyway.
RV also complained about the "C" locale being used, when "UTF-8" is what it wants. I thought I had fixed this previously, but I had to unset other env variables for …
=> Qt6: fix opengl and "C" locale warning on macOS

.gitignore
n/a
Added three more Mu scripts that are generated by CMake to prevent accidental commits of those files.
Prevent accidental commits of those files.
=> Ignore Mu scripts that are generated with CMake

docs/build_system/config_windows.md
Fix clarity about which msys2 to use. 
Selecting the wrong msys2 could cause the build/setup to fail
n/a: documentation
added 2 lines of documentation.
n/a
=> Fix clarity about the correct msys2 to use

src/lib/app/RvCommon/ui/RvPreferences/Qt6/RvPreferences.ui
none
Fix typo in preference pane
(Changed "Asyn" to "Async")
Typo = bad
macOS
=> SG-None: Fix typo (asyn -> async)

docs/build_system/config_linux_rocky89.md, docs/build_system/config_macos.md, docs/build_system/config_windows.md
n/a
Standardize the documentation with the VFX tabs and update Windows to mentions Qt 6.
Documentations layouts were not standardize for all platforms.
**Link to the documentation based on this PR:**
https://cedrik-openrv-fork.readthedocs.io/en/standardize-docs
=> Standardize the documention and update windows documentations
