AcademySoftwareFoundation/OpenRV

cmake/dependencies/qt5.cmake

This PR adds two cached variables for the Qt5 dependency:
- `RV_DEPS_QT5_RESOURCES_FOLDER` (defaults to `"${RV_DEPS_QT5_LOCATION}/resources"`)
- `RV_DEPS_QT5_RESOURCES_FOLDER` (defaults to `"${RV_DEPS_QT5_LOCATION}/translations"`)
The variables can be set like this:
```
$ cmake -B cmake-build \
-DRV_DEPS_QT5_LOCATION=/usr/lib64/qt5 \
-DRV_DEPS_QT5_RESOURCES_FOLDER=/usr/share/qt5/resources \
-DRV_DEPS_QT5_TRANSLATIONS_FOLDER=/usr/share/qt5/translations
```
Feel free to correct this @geffrak if you were thinking about something else!

Cmake: add Qt5 `resources` and `translations` folder variables

---

doc/build_system/config_macos.md

changing it to the correct default installation path and same version of Qt as described in line 46.
Signed-off-by: finnschi <47210121+finnschi@users.noreply.github.com>

Fix errors in Build Guide for MacOS

---

cmake/dependencies/boost.cmake

On my MacBook with macOS Ventura and Xcode 14.2, when I try to rebuild the "RV" target using Jetbrains CLion, it always rebuilds everything that depends on Boost.
Debugging with `-d explain` tells me that RV_DEPS_BOOST gets constantly rebuilt because of some boost dylibs listed in the BUILD_BYPRODUCTS not existing.
Example of the issue:
```
/opt/homebrew/bin/cmake --build /Users/geffrak/code/git/github.com/org-geffrak/OpenRV/cmake-build-debug --target RV -- -d explain 
ninja explain: output RV_DEPS_BOOST/install/lib/libboost_atomic.dylib doesn't exist
```
Before this commit, `_boost_libs` contains libraries that are not requested to the build of Boost. With this change, we explicitly request stuff to the build of Boost using that list.
None of the removed libraries are used by OpenRV, and …

Correct boost.cmake byproducts

---

src/lib/mu/Mu/Thread.cpp

Fix error when building on Linux (At least on Arch Linux)
Signed-off-by: adro79 <57686179+adro79@users.noreply.github.com>

Thread.cpp: change ucontext to ucontext_t

---

src/build/make_pyside.py

Adding an explicit `False` check in case the downloading archive doesn't have any CRC record.

fix 7z archive check for libclang

---

src/lib/base/TwkUtil/SystemInfo.cpp

Closes #20 
The sysctl include is not needed on CentOS7 and as of glibc 2.32 it has been removed.  So support distros/compilers later than that by removing it completely on Linux.

Include sysctl on Mac only

---

doc/build_system/config_linux_centos7.md

The link to devtoolset-9 in the CentOS build guide is dead and I couldn't find any other good equivalents that described what it was, so I just removed the link.  The instructions below describe how to install it from yum, and that's all that is really needed.
This was report in issue https://github.com/AcademySoftwareFoundation/OpenRV/issues/38

Remove dead link

---

doc/build_system/config_linux_centos7.md
doc/build_system/config_macos.md
doc/build_system/config_windows.md

* Windows's documentation referenced a link to https://account.qt.io, which is the route for commercial users of Qt to get the installer.
* Clarify how to get JOM.
* Using the exact wording on all three platforms.
* Warnings about other sources of Qt.
Signed-off-by: Kerby Geffrard <kerby.geffrard@autodesk.com>

Improve the documentation on how to get Qt

---

src/plugins/rv-packages/otio_reader/PACKAGE
src/plugins/rv-packages/otio_reader/genericEffectHook.py
src/plugins/rv-packages/otio_reader/manifest.json
src/plugins/rv-packages/otio_reader/otio_reader.py

This branch fixes a problem from a client OTIO that was being imported to RV.
The problem was that there was an audio clip which had no `available_range` on an audio-only clip (which is valid OTIO), so we would throw an exception when we tried to access its `start_time` property.
To fix it, we will use `trimmed_range` if no `available_range` is available.  This will mean the media will have exactly the same number of frames as the source (ie trimmed/ no handles) in these cases.
There were also a number of Effects were generating errors, so I added a hook for the generic Effect that will just print that we do not support effect [effect_name].  Users can add their own custom handling here for their effects.

Fix OTIO import problem when no available_range on audio

---

src/lib/ip/IPBaseNodes/IPBaseNodes/SwitchIPNode.h
src/lib/ip/IPBaseNodes/SwitchIPNode.cpp
src/plugins/rv-packages/otio_reader/otio_reader.py

This is bringing back a fix I did earlier, but after the branch off for OpenRV, so it wasn't part of the initial OpenRV code.  The issue is that when we have a switch node.  Here's my original PR description:
This branch fixes the timing when a Sequence node without autoEDL is connected to a SourceNode via a SwitchNode. Normally, the SwitchNode is computing an offset for autoEDL mode so that its frames are always starting at 1 (so it can basically unwrap the autoEDL behaviour to find the real frames). With autoEDL though, raw frame numbers are input so we do not want this. The simplest fix I can think of is to pass the autoEDL mode in the context when we metaEvaluate the graph when computing the ranges. This way if we are connected to a Sequence node with autoEDL disabled, we can ignore …

Fix switch node EDL timings

---

src/lib/app/RvCommon/RvApplication.cpp

SG-29809: Fix unable to write RV settings on Windows
1. Description of changes
This commit fixes the following Open RV reported issue on Windows:
https://github.com/AcademySoftwareFoundation/OpenRV/issues/53
RV settings (QSettings) default location on Windows is obsolete ([home]/Application Data)
Qt automatically falls back to the default [home]/AppData location but in some environment/users, an error is reported. I was not able to reproduce this error and even the user who reported it said that it was giving an error on his laptop but not on his workstation.
Now using QStandardPaths::writableLocation(QStandardPaths::AppDataLocation) which maps to [home]AppData/Roaming on Windows and validated that the OpenRV.ini file is correctly saved to the same location as before (AppData/Roaming). …

SG-29809: Fix unable to write RV settings on Windows

---

src/build/make_pyside.py

Patch the PySide2 build to not use libXSLT.
Since the last update of MacOS (or Xcode.app?), we can't build PySide2 anymore. The issue seems caused by the way PySide2 finds and uses libXSLT. It's mixing multiple versions of MacOSX.sdk.
MacOS 13.3, Xcode 14.3.

Fix PySide2 build break with recent macOS/Xcode.app

---

.readthedocs.yaml
cmake/defaults/cxx_clang_defaults.cmake

None
Fix readthedocs build fails
ReadTheDocs builds are failing on the main Open RV repo. The reason was the the build would try to run pip as specified in .readthedocs.yaml. The inclusion of pip was a mistake.
Built successfully in OpenRV fork.
Edited: .readthedocs.yaml: removed the pip requirements and its associated build dir.

Fix readthedocs publication fails

---

src/lib/app/RvCommon/MuUICommands.cpp

Fix out of bounds memory access in httpGet command
Segfault when testing httpGet in custom package.
macOS 13.2.1
Test script below no longer crashes, prints contents of github.com to console:
`RV.app/Contents/MacOS/RV -pyeval "from rv import commands; onReplyEvent = lambda event: print(event.contents()); commands.bind('default','global','on-reply-event', onReplyEvent, 'desc'); commands.httpGet('https://github.com', [], 'on-reply-event');"`
Parameter index corrected in MuUICommands.cpp

[116: Fix segfault in httpGet command]

---

cmake/dependencies/openexr.cmake

Fixes #106 
this is to fix DWAA compressed EXR files crashing openRV on windows
Tested and built on windows 10 , needs to be built tested on macOS and linux before merge. 
Updated both hash and version

[ 106: Update openexr to 3.1.7 ] 

---

src/lib/mu/MuLang/MuLang/generated/.gitignore
src/lib/mu/MuQt5/MuQt5/QFileType.h
src/lib/mu/MuQt5/QFileType.cpp

Fix rv_nuke package crash when installing support files [SG-29358]
Cause: It turned out that the cause of the crash was that the QFile::open() method had no mapping whatsoever in Mu. 
Solution: Added the QFile::open() method to the MuQt5 binding. 
This commit fixes the crash with the rv nuke integration package when selecting the 'Nuke/Install Nuke Support Files' RV Nuke package menu option. 
This commit was successfully built on all 3 platforms and tested on CentOS 7.9.

Fix rv_nuke pkg crash when installing supprt files

---

src/lib/app/RvApp/CommandsModule.cpp
src/lib/app/RvApp/RvApp/RvSession.h
src/lib/app/RvApp/RvSession.cpp
src/lib/app/mu_rvui/commands.mud
src/lib/app/py_rvui/rv_commands_setup.py
src/lib/ip/IPBaseNodes/SourceGroupIPNode.cpp

Rename the MMR switch groups to something more meaningful [SG-28740]
With the new Multiple Media Representations feature, the ui names of the source nodes and switch nodes were not really meaningful. 
In this commit, the media representation name is used as the ui name by default.
The MMR switch groups and sources displayed in the Session Manager now use names that are now more meaningful. [SG-28740]
This commit was successfully built on all 3 platforms and tested on macOS Monterey.
Signed-off-by: Bernard Laberge <bernard.laberge@autodesk.com>

Rename the MMR switch groups to something more meaningful

---

src/lib/ip/IPBaseNodes/FileSourceIPNode.cpp

Fix RV crashes when RV_SOURCE_TILING=1 [SG-28211]
In the scenario reported by a customer, a large 1444x94605 image is used with RV_SOURCE_TILING=1 to prevent any filtering in 1:1 view mode in RV. Random crashes were being reported. 
The RV_SOURCE_TILING mechanism effectively dissects the original texture in tiles that can be processed by the GPU without being downscaled. Each tile being a child in memory of the original texture. 
The random crashes were caused by the last tile which could end up being 1 line too big, effectively overshooting the original texture by one line due to rounding in the float to integer conversion. 
Now making sure that the last tile does not overshoot the original parent buffer by clipping that extra line if necessary. 
This commit fixes some intermittent …

Fix RV crashes when RV_SOURCE_TILING=1

---

src/lib/ip/IPMu/CommandsModule.cpp

Add missing redraw in setMargins() command [SG-28734]
Add missing redraw in setMargins() command.
Note that all the simple commands, like setFrame() for example, calls askForRedraw(). 
setMargins() was not. 
Fixed the missing redraw when using the setMargins() RV command. [SG-28734]
This commit was successfully built on all 3 platforms and tested on
macOS Monterey.
Signed-off-by: Bernard Laberge
[bernard.laberge@autodesk.com](mailto:bernard.laberge@autodesk.com)

Add missing redraw in setMargins() command

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp
src/lib/ip/IPBaseNodes/FileSourceIPNode.cpp

Fix RV unable to open pre-signed S3 URLs [SG-29243]
An RV user reported they couldn't File Open pre-signed S3 URLs. 
Now I always assumed (incorrectly) that RV did not support File/Open pre-signed URLs. 
Now it looks like this limitation was OS specific because of the boost::filesystem::exists() that is called when File/Open a pre-signed URL. 
It looks like boost::filesystem::exists() complies to the maximum path length on each OS: 
260 on Windows 
1024 on Mac 
4096 on CentOS 
Note that I also tested std::filesystem::exists() and it behaves just like the boost one. 
Which is expected because I believe std::filesystem originates from boost::filesystem. 
In this commit, I made sure to NOT call boost::filesystem::exists() if the movie path is a URL. 
I was able to validate this fix on Mac, …

Fix RV unable to open pre-signed S3 URLs

---

src/lib/app/RvCommon/RvBottomViewToolBar.cpp
src/lib/ip/IPCore/IPCore/ImageRenderer.h
src/lib/ip/IPCore/ImageRenderer.cpp
src/lib/ip/IPCore/Session.cpp

Fix viewer not updated after RV reload() command [SG-30348]
The RV reload() command which is used by the "RV/Tools/Force Reload..." menu options instructs RV to reload media files. 
The command works as expected except for the current frame which never seems to be updated. 
However, if one selects the next frame and then goes back to the previous frame then the viewer gets updated. 
This clunky work around is not available when viewing a single frame which is why the client is interested into a fix for this issue. 
The client tested the issue on multiple versions of RV and confirms that this regression was introduced in RV 7.1 (2015) 
I found the cause of the regression which had to do with the RV's Image Renderer refactoring that took place in RV 2015.
In the refactored image renderer, …

Fix viewer not updated after RV reload() command

---

src/bin/python/py-interp/main.cpp
src/lib/app/PyTwkApp/PyInterface.cpp

Set Python multiprocessing.set_executable [SG-30002]
Python's documentation recommends that python embedders set the path of the Python interpreter to use when starting a child process. 
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_executable 
This commit fixes a Python issue in RV by allowing the use of multiprocessing.pool.Threadpool. [SG-30002]
This commit was successfully built on all 3 platforms and tested on macOS Monterey.
Signed-off-by: Kerby Geffrard <kerby.geffrard@autodesk.com>

Set Python multiprocessing.set_executable

---

src/lib/ip/IPBaseNodes/IPBaseNodes/SequenceIPNode.h
src/lib/ip/IPBaseNodes/IPBaseNodes/StackIPNode.h
src/lib/ip/IPBaseNodes/SequenceIPNode.cpp
src/lib/ip/IPBaseNodes/StackIPNode.cpp
src/lib/ip/IPCore/IPCore/IPImage.h
src/lib/ip/IPCore/IPImage.cpp
src/lib/ip/IPCore/ImageRenderer.cpp

Add property to sequence and stack to disable reversed blending mode
To support per-segment blending modes, the SequenceIPNode node was enhanced with a property-container to 
handle per-input blending modes. 
Since ImageRenderer::renderAllChildren did not properly support multiple 
blend modes, I had to add a flag to disable reverse-order blending. 
Reverse-order blending is a mechanism that seemed in place for shader-based 
compositing (currently disabled) and that sometimes inverses the order in 
which inputs are composited. This means that in RV the first input of a 
LayoutGroup becomes the top layer (lastly blended). This also has the side 
effect of forcing a "Replace" blend mode on the first drawn input. I would 
have prefered to completely remove this mode, but this would have …

Add property to sequence and stack to disable reversed blending mode

---

src/plugins/rv-packages/ocio_source_setup/PACKAGE
src/plugins/rv-packages/ocio_source_setup/ocio_source_setup.py

Fix OCIO issues after reloading an RV session [SG-29679]
After reloading an already OCIO corrected RV session, any sources added in RV afterwards does not get properly color space identified. 
Another side effect of the same issue: It is not possible to de-activate the OCIO correction on a per source basis in that same scenario. 
Before this commit from 7 years ago, the default (non OCIO) pipelines were assumed to be: 
DEFAULT_RV_PIPE = { 
"RVLinearizePipelineGroup": ["RVLinearize", "RVLensWarp"], 
"RVLookPipelineGroup": ["RVLookLUT"], 
"RVDisplayPipelineGroup": ["RVDisplayColor"], 
} 
With this commit from 7 years ago, then the default RV pipelines could be anything since it assumed to be the first one being encountered. 
Now the problem with this approach is what if the first correction …

Fix OCIO issues after reloading an RV session

---

src/lib/app/RvApp/RvSession.cpp
src/lib/app/mu_rvui/commands.mud
src/lib/ip/IPMu/CommandsModule.cpp

Fix dup MMR UI entries when enabling PresentationMode [SG-30496]
In RV 2023, we've added a new MMR UI when multiple sources are present at the current frame 
Now one of our QAs found out that when presentation mode is enabled with a single source present on the timeline then the MMR UI lists a duplicate of the same source in the UI. 
This is caused by the RV commands sourcesAtFrames() which does not guarantee the uniqueness of the sources returned. When presentation mode is enabled, then the same sources are listed twice causing this issue. 
Modified sourcesAtFrame() command so that the same source is only listed once while preserving the order because some code might have relied on it (it is customary for RV code (client code or our own) to fetch the sourcesAtFrame() and then only apply …

Fix dup MMR UI entries when enabling PresentationMode

---

src/bin/apps/rv/main.cpp
src/bin/nsapps/RV/main.cpp

Disable Qt's HDPI environment variables [SG-30447]
Fix corruption when playing media with inserts [SG-29243]
If RV_QT_HDPI_SUPPORT is not set, unset QT's scaling environment variables because RV is known to not work well with them.
Added the RV_QT_HDPI_SUPPORT environment variable for systems connected to a high DPI monitor. This new environment variable controls whether or not RV considers the QT environment variables defined on the system that might be used by other software. If RV_QT_HDPI_SUPPORT is set, RV uses the QT environment variables set on the system. If not, RV ignores any external QT environment variables. [SG-30447]
This commit …

Disable Qt's HDPI environment variables

---

src/lib/ip/IPBaseNodes/SwitchIPNode.cpp

Fix flickering Sequence with SwitchNodes issue [SG-28820]
A flickering render issue was uncovered while testing for another issue: OTIO : Zooming out of the default output bounds does not reveal media.
I have identified the source of the flicker and I can even reproduce it without the recent otio modification. 
The flickering issue only occurs when a switch node is connected to an RV Sequence and that the underlying Source node has a DVE transformation applied to it. 
If one changes the view node to point directly to the Switch node then everything renders well without flickering. 
Same good rendering without flickering if one changes the view node to point to the Default Stack or the Default Layout. 
Now I have identified the root of the issue: 
It is caused by the …

Fix flickering Sequence with SwitchNodes issue

---

src/plugins/rv-packages/multiple_source_media_rep/PACKAGE
src/plugins/rv-packages/multiple_source_media_rep/multiple_source_media_rep.py
src/plugins/rv-packages/multiple_source_media_rep/multiple_source_media_rep_utils.py

Add multiple sources at frame support to MMR UI [SG-28863]
The original design of the Multiple Media Representations (MMR) did not address the use case of having multiple sources at the current frame. The current implementation is always showing/controlling the first source in the list: 
This commit implements the following: 
When multiple sources at the current frames are involved, then we populate the MMR UI menu differently : 
1. We first add the union of all the sources's media representations to the menu 
2. Then add each source's media representations to the menu 
This is what it looks like: 
When the sources are not sharing that exact same media representation, then 'Mixed' is shown in the MMR button menu: 
We added the ability to select specific sources to specific clips when …

Add multiple sources at frame support to MMR UI

---

docs/build_system/config_linux_rocky9.md
rvcmds.sh

This provides a build guide for Rocky 9.  It's similar to the CentOS build guide, but Rocky9 is a lot more minimalistic out-of-the-box, so a number of build requirements that are pre-installed on CentOS are not on Rocky9.  Thus using the CentOS build guide is not ideal since those missing packages must be manually tracked down.  This new guide is intended to make life easier for Rocky/RHEL9 users. 
I also fixed the rvcmds to base the script home on the shell scripting language instead of the OS, since the two were being conflated. It's the shell version and not the OS that determines the right command.
Tested on a fresh install of Rocky 9.1.

Rocky 9 Build Guide

---

cmake/install/pre_install_darwin.cmake

This branch fixes the Mac installation.
The problem is the CMake variable `PROJECT_SOURCE_DIR` is not available on the install step (only configure and build).  Since no variables involving the source dir are present at installation time, the only suitable replacement I could find was to use a path relative to the current directory `CMAKE_CURRENT_LIST_DIR`.  
Tested on Mac 13.3.1

Fix Mac install

---

docs/rv-manuals/rv-user-manual/rv-user-manual-chapter-two.md

Update Open RV documentation rv-user-manual-chapter-two.md with Proxy Configuration and Self-Signed Certificates information.
We're trying to keep the documentations for Open RV and RV in sync where it makes sense. This PR is part of that effort.

Synchronize documentation with RV 2023

---

CONTRIBUTORS.md

Use bullet points for all contributors.
The original contributors were not listed in bullet point form like the OpenRV contributors.  This makes them both use bullet points.

Use bullet points for all contributors

---

CONTRIBUTORS.md

[ Add missing contributor ]
This branch adds a missing contributor to the original RV to the list.

Add missing contributors

---

src/build/make_openssl.py

https://github.com/openssl/openssl/issues/18225
Removes the `no-asm` flag to OpenSSL's build to build with the assembly language routines.
When compiling OpenSSL using Xcode 11, disabling the assembly language routines breaks the TLS 1.2 support.
Tested on MacOS Ventura 13.3.1 with an Apple Silicon SoC.
The change will get applied to all 3 OSes to have the same behaviour on all OSes, but I didn't test on all 3 OSes yet. The additional tests will get executed once we pull that commit into ShotGrid RV's internal CI.

OpenSSL: Re-enable assembly language routines

---

src/plugins/rv-packages/annotate/PACKAGE
src/plugins/rv-packages/annotate/annotate_mode.mu

Added the _hideDrawPane variable to keep track of when to hide the draw pane. This will allow the closure of the annotations panel when "Select/Scrub Time" Tool is selected.
Variable has 3 stages: 
0 - Initial value/Nothing selected
1 - When the "Select/Scrub Time" Tool is selected
2 - When the "Select/Scrub Time" Tool is selected and the 'x' icon is selected

Added variable to fix the annotations panel closure bug

---

docs/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-two.md

None. This is a trivial fix.
Describe how to delete cleanly a source from the image graph. 
The documentation describes how to use `addSourcexxx()` to add a source to the image graph, but did not explain that simply deleting the returned node did not clean up the graph. This update fixes that.
Only updated file is [Ref Manual: Chapter Two](docs/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-two.md)
Note that some trivial markdown clean up also happened. The only area of concern is section 2.3.2 Deleting a Source.

Add a section on how to delete sources via the api

---

cmake/install/pre_install_linux.cmake

[Strip debug symbols from binaries when installing release on Linux]
This brach adds some additional code to the RV installation step. When executed it will check the file to be installed to see if its a binary, and if so strip out any debugging symbols it finds. Certain mime types that cause errors with the strip command have been filtered out, and an error message will be displayed on any types that may fail in the future indicating that they may need to be added to the ignore list.
I did this at installation time instead of build time (with the -s option in CXX_FLAGS) so that we would also strip third-party binaries that we install, since we don't pass out CXX_FLAGS down to them when we build them.
It will reduce the size of the linux installation and should improve load performance. …

Strip debug symbols from binaries when installing release on Linux

---

src/lib/ip/IPCore/IPGraph.cpp

Fix RVIO getting stuck at rendering the first frame [SG-30920]
This is an RVIO only issue: in some situations where the audio did not exactly match the video, the RVIO rendering of an RV session was getting stuck at rendering the first frame. The same session loaded in RV rendered just fine.
Note that RVIO does not have a dedicated audio thread to fetch the audio. It relies on the main thread to do so. 
In that particular user scenario, the audio rendering was caught in an infinite loop because of the following condition:
while (secondsBuffered <= audioMaxCache)
In that particular scenario, the secondsBuffered was exactly equal to the audioMaxCache.
Changed the <= with a < so that once the audio cache is filled we exit the audio rendering loop: 
while (secondsBuffered < audioMaxCache) …

Fix RVIO getting stuck at rendering the first frame

---

src/lib/app/mu_rvui/commands.mud
src/lib/ip/IPCore/Session.cpp
src/lib/mu/MuPy/PyModule.cpp

Fixes #120 
Fixes #118 
Fixed the gltext memory leak by fixing the PyUnicode_AsUTF8String() which was used without its associated Py_XDECREF().
Note that this memory leak occurred not only in gltext but also whenever an Python RV package was calling an RV cmd with text parameters.
This fix addresses the following Open RV reported issue:
https://github.com/AcademySoftwareFoundation/OpenRV/issues/120
Using gltext seems to cause a memory leak issue.
The reporter provided an example mode that creates a watermark using gltext that shows the issue, however it seems to also happen with the Color Inspecter tool shipped with Openrv (uses gltext). Memory usage of RV will continue to increase causing RV to slow down and or eventually crash.
I was able to identify the source of the memory leak using …

120: Fix gltext memory leak (and other mem leaks)

---

cmake/install/pre_install_linux.cmake

[Fix Linux install]
A few of the PySide libraries generated on CentOS7 are not able to be stripped because they are too large for strip to handle.  To workaround this issue, I simply changed the strip error from fatal to a warning. 
I also added an additional mime type for fonts that strip was failing on to the ignorelist. 
Tested on CentOS7

Fix Linux install

---

src/build/make_pyside.py

Fixes #169 
Fixing build error that happens during a rebuild for Python/PySide
Tested rebuilding on Windows 11.
Fixing FileExistsError by removing the 'CMakeLists.txt.old' before renaming the current CMakeList file

Issue-169: [Bug]: OpenRV fails to rebuild on Windows

---

src/lib/app/RvCommon/RvBottomViewToolBar.cpp

Added tooltips to the six playback buttons since the other buttons have tooltips and these did not. Tested on Windows 10.

Add tooltips to play buttons

---

cmake/macros/rv_stage.cmake
src/build/make_pyside.py
src/lib/app/RvPackage/PackageManager.cpp
src/lib/app/RvPackage/RvPackage/PackageManager.h

When creating a package you can list folders with files that should be installed in the SupportPath Plugins folder rather than listing each file individually
It should be easier/quicker to create packages
MacOS
- Packages are zipped with directory structure
- All files in package and its directories are zipped
- The app will traverse the PACKAGE file and see the list of folders specified. Based on this, all files under the folder and its subdirectories will be added to location provided.
N.B. When creating PACKAGE file if you want to use new behaviour it takes the following format:
folders:
- folder: [FolderName]
location: [LocationName]

Add Support for Directories in RV Packages SupportPath

---

cmake/macros/rv_stage.cmake

In #161, I introduced a change to clean the RV_PACKAGE_LIST at each configure stage so that if we update a package version, we don't have the old package in the RV_PACKAGE_LIST. This behaviour is buggy, so I prefer to revert that bit and try again another time with another approach. 
It breaks the rvinstall target that installs all the packages. 
I tested on MacOS Ventura, but it's pretty much platform agnostic. 
N/A
N/A

Properly install RV_PACKAGE_LIST with rvpkg at the end of the build

---

src/build/make_openssl.py

Reverts #150 on Windows.
There are reports in the field that there are build failures related to nasm on the OpenSSL build. It seems to work fine in my test environment, but not everywhere. It's safe to disable it on Windows since it was disabled at first. It only got enabled because it was required on MacOS and I wanted to have the same configuration on all 3 platforms.
It's a revert. It's the configuration that is being used in the Commercial RV build.
N/A
N/A

Disable OpenSSL asm runtimes on Windows

---

cmake/macros/rv_stage.cmake
src/lib/app/RvPackage/PackageManager.cpp
src/lib/app/RvPackage/RvPackage/PackageManager.h

When creating a package you can list folders with files that should be installed in the SupportPath Plugins folder rather than listing each file individually
It should be easier/quicker to create packages
MacOS, Windows, Linux
Add a list of changes, and note any that might need special attention during the review.
Packages are zipped with directory structure
All files in package and its directories are zipped
The app will traverse the PACKAGE file and see the list of folders specified. Based on this, all files under the folder and its subdirectories will be added to location provided.
N.B. When creating PACKAGE file if you want to use new behaviour it takes the following format:
folders:
folder: [FolderName]
location: [LocationName]

Directory support for rv packages

---

cmake/macros/rv_stage.cmake

Adds the rv package content as a dependency to the .rvpkg file generation command.
When working on a package, building RV will now re-build and re-install the package.
I had this change locally on my Mac while implementing a new feature and it's working well.
N/A
N/A

Rebuild packages on file changes

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp

This is a followup to my last branch that added an event medialibrary.  I forgot to include the file that actually adds the headers sent by the events to the ffmpeg request.

Add http headers to ffmpeg request

---

src/lib/app/EventMediaLibrary/CMakeLists.txt

Fix the build.
The build on Linux is broken because of a missing dependencies on `Qt5::Core`
The file `EventMediaLibrary.cpp` includes `<QtCore/QUrl>` so we need to link with the `Qt5::Core` library.

Fix build on Linux

---

src/lib/ip/IPCore/IPCore/Session.h
src/lib/ip/IPCore/Session.cpp

Added a new bool var in Session.cpp to check for a certain event (before-progressive-loading) that happens before the "after-progressive-loading" event.
The m_postFirstNonEmptyRender variable used to delay the window fitting calls would always be called after launching RV, because an "after-progressive-loading" event is launched even if there are no media loaded (see RvApplication.cpp L:744).
The "before-progressive-loading" event is now used to prepare to check for the "after-progressive-loading" event. Because the former should only be called when media is wanting to get loaded.
There could have been a possibility to remove the "after-progressive-loading" event call in RvApplication.cpp, but since Session.cpp is not the only listener/receiver of events, it didn't feel wise to do. 
The …

Fit first media correctly after launching RV

---

cmake/dependencies/CMakeLists.txt
cmake/dependencies/ffmpeg.cmake
src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp
src/lib/image/MovieFFMpeg/MovieFFMpeg/MovieFFMpeg.h
src/lib/image/mio_ffmpeg/CMakeLists.txt

[ Enable optional FFmpeg and mio_ffmpeg customization ]
These small changes are required so that one can customize both FFmpeg and mio_ffmpeg if say one project was to consume Open RV as a submodule.
-  Only add cmake custom target 'dependencies' but only if it hasn't been created already (ADD_CUSTOM_TARGET(dependencies))-To allow a project consuming Open RV as a sub-module to add the target first.
-  FFmpeg.cmake : Add an optional post_configure_step that is added only if the RV_FFMPEG_POST_CONFIGURE_STEP cmake variable is defined-To allow applying patches/customization to FFmpeg.
- mio_ffmpeg : Skip building of Open RV mio_ffmpeg if cmake var OPEN_RV_SKIP_MIO_FFMPEG is set (optional) - To enable a project consuming Open RV as a sub-module to build its own customized version.
- …

Enable optional FFmpeg and mio_ffmpeg customization

---

cmake/dependencies/ffmpeg.cmake
cmake/dependencies/openssl.cmake

Changed the copy_implibs step for the Windows build
RV_DEPS_OPENSSL_LIB_DIR doesn't exist anymore, so the paths are wrong

Fix Windows FFMpeg build error

---

CMakeLists.txt
README.md
cmake/dependencies/atomic_ops.cmake
cmake/dependencies/boost.cmake
cmake/dependencies/gc.cmake
src/build/make_python.py

N/A
Unset macOS deployment target related variables so everything relies on the MACOSX_DEPLOYMENT_TARGET environment variable.
Prior to this change, the macOS deployment targets were all over the place because all third parties had it defined in different methods, now we set the environment variable that the compiler understands so everybody have it properly set. 
Tested on MacOS Ventura. Without MACOSX_DEPLOYMENT_TARGET, `otool -l path/to/lib | grep minos` returns 13.0, and setting MACOSX_DEPLOYMENT_TARGET=11.0 gives me 11.0. (excluding Qt which is precompiled)
N/A
N/A

Native MACOSX_DEPLOYMENT_TARGET support

---

src/plugins/rv-packages/session_manager/PACKAGE
src/plugins/rv-packages/session_manager/session_manager.mu

Fix RV crashes when creating new viewable stack
This PR fixes RV crashes when creating a new viewable stack
In RV, one can use the Session Manager to select multiple layers of an OpenEXR image file and create a viewable stack with them:
Since RV 2021.0.3, this workflow makes RV crash.
This issue was introduced in RV 2021.0.3. 
It is an unfortunate side effect of a cleanup we did with the before-progressive-loading and after-progressive-loading events (they were not consistently generated).
The crash occurs because the QTreeView is being modified behind the scene while we iterate through its elements.
Now there is a variable dedicated to disabling the updates while we are iterating through the QTreeView : _disableUpdates. But the after-progressive-loading event automatically re-enable the …

Fix RV crashes when creating new viewable stack

---

src/lib/ip/IPBaseNodes/FileSourceIPNode.cpp

A user reported some RV crashes on Windows when a session file contained file sources with unreachable media (because the media was not available locally).
We were not able to reproduce until the client informed us that the crashes were only occurring when the multiple files associated with a single file source in the RV session were not ALL available. 
That was the key that allowed me to reproduce the issue.
Normally, an RVFileSource is only comprised of a single file. However, RV also supports stereoscopic images (left + right) and also having the audio file separated from the video file. The latter was the user case here.
In the scenario that was causing the crash, an RVFileSource was composed of a media file (an openEXR image) which was NOT available locally, and an audio file (a …

Fix crash when loading a multi-files src with mixed avail

---

cmake/dependencies/spdlog.cmake

This commit fixes the windows debug build 
When spdlog is built in debug, the 'd' suffix is added to the resulting static lib by the spdlog build system.
This 'd' suffix was added to the spdlog.cmake and I took the opportunity to do some cleanup.
Also, the CMAKE_BUILD_TYPE was NOT passed to the spdlog build on Mac+Linux. I fixed that too.
Tested on all platforms in both debug and release

Fix Windows debug build caused by spdlog

---

docs/rv-manuals/rv-mu-programming.md
docs/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-four.md

A user reported that the fourth chapter of the RV reference manual contained examples that were using outdated syntax and therefore could not be executed.
I have tested all the examples in the fourth chapter of the RV reference manual and two of them had outdated syntax which was corrected in this commit.
Additionally, a note was added to the Mu documentation to inform the user that the recommended RV scripting language is Python (not Mu).

Fix examples in doc not working because of outdated syntax

---

src/lib/app/RvPackage/PackageManager.cpp

The settings are now loaded with the appropriate QSettings depending on if RV was started with _-noPrefs_ or not.
When starting RV with _-noPrefs_, the current preferences were ignored, but they were overwritten with the default values when closing RV.
The bug was tested on MacOS.
1. Launch the latest RV build
2. Go into _OpenRV / Preferences / General_ and change the font size to 15
3. Restart RV and make sure the font size is still 15
4. Close RV and restart it with _-noPrefs_
5. The font size is 13, which is the default value
6. Close RV and restart it again without any argument
7. The font size is now back to 15 like expected instead of 13

Fix -noPrefs cmd line arg that was resetting prefs

---

cmake/dependencies/oiio.cmake
cmake/dependencies/webp.cmake
src/lib/ip/IPCore/IPCore/ShaderFunction.h
src/lib/ip/IPCore/ShaderFunction.cpp
src/lib/ip/OCIONodes/OCIOIPNode.cpp

N/A
The version comparison doesn't even check the GLSL version, maybe it should. For higher than GLSL 150, we will keep the current code. If the version is less than 150, we will use "version 120" as the header and remove the extension GL_ARB_texture header.
Mac fails to build with the current GLSL header.
Tested on Mac Ventura 13.2.1, Rocky 8 Dbg config.
Removing OCIO dep from OIIO as our OIIO config doesn't need OCIO 
Fixing byproducts for WebP on Mac and Linux for iterative builds 
Tweaking OCIO pipeline code in OCIOIPNode and setting the GPUProc as OPT_DEFAULT instead of OPT_NONE. ocioconvert uses OPT_DEFAULT for legacy 
Fixing bad GLSL Version comparison for Mac. We may need to iterate on this fix 
Fixing the Annonate Output when GLSL fails as it wasn't showing the exact GLSL that …

Issue-162: OCIO v2 configs don't work on Mac; shader compiler fail

---

src/bin/apps/rvpush/RvPusher.cpp

The rvpush command can now be run to merge sessions with a tag name containing underscores.
Two sessions were being created instead of merging them into the same one when the tag name had underscores it in.
The bug was tested on MacOS.
```
// Run this command
./rvpush -tag "tag_name" merge "Movie1.mov"
// And this one
./rvpush -tag tag_name merge "Movie2.mov"
```
You should now have both video files inside the same RV session.

Fix rvpush not merging sessions when tag name has underscores

---

cmake/dependencies/python3.cmake

Updates `DOWNLOAD_NAME` to use `_python3_version` as `_version` isn't declared in this file.
The downloaded package ended up with the wrong version string. In initial testing this was was the version from OpenSSL.
Tested that it builds in a virtual machine for Centos 7

Fix download_name for python3

---

src/lib/ip/OCIONodes/OCIOIPNode.cpp

The idea is to only call _OpenColorIO_v2_2::ColorSpace::getName()_ if the OCIO environment variable is set.
Using the new OCIOv2 system, if a user uses rvio to export a .rv session file in which some OCIO configs were applied clips, everything works as expected as long as the OCIO environment variable is detected in the terminal in which rvio is used. However, if the OCIO environment variable is not set, the tool will reach a segmentation fault. This is a regression. Using a past release of RV (i.e 2023.0.1), the tool would export the content from the .rv session file but would just not apply the OCIO changes if it couldn't find the environment variable.
The bug was tested on MacOS.
1. Download the attached zip file containing OCIO configs from …

Fix segmentation fault if OCIO is not set

---

src/lib/base/TwkUtil/FileLogger.cpp
src/lib/base/TwkUtil/TwkUtil/FileLogger.h

A synchronous version of the spdlog logger can now be used to get some logs to debug RV on crashes.
With the async nature of the logger, the logger file was empty if a crash occurred since the content of the logger's buffer didn't had the time to flush its content to disk.
The feature was tested on MacOS.
Using commercial RV (so that you can have access to the Python Console):
1. Change `static ENVVAR_BOOL(evFileLogSynchronous, "RV_FILE_LOG_SYNCHRONOUS", false);` to `static ENVVAR_BOOL(evFileLogSynchronous, "RV_FILE_LOG_SYNCHRONOUS", true);`
2. Rebuild and lauch RV
3. Select _Tools/ShotGrid Python Console_ in the menu bar
4. Enter the following code snippet:
```
import rv.commands as rvc
rvc.crash()
```
5. Execute it
6. Open the file logger, and should have logs instead of nothing

Add synchronous spdlog logger to debug crashes

---

src/build/make_pyside.py

N/A
Changing python3.9 to python3.10 in make_pyside.py so the python EXE is copied
The build is broken for Mac and Linux since make_pyside.py cannot find Python
Mac Ventura and Linux Rocky 8
- Fixing code line with old python version. I'll create a story to investigate improving this code since it wasn't revisited since movign to CMake and creating the OpenRV repo.

VFX2023: Updating third party components for CY2023

---

cmake/dependencies/oiio.cmake

Changed the download hash for the OpenImageIO's code.
We believe this change was caused by the fact that the tagged oiio sources are now hosted by ASWF.
From:
https://github.com/OpenImageIO/oiio/archive/refs/tags/v2.4.6.0.tar.gz
To:
https://github.com/AcademySoftwareFoundation/OpenImageIO/archive/refs/tags/v2.4.6.0.tar.gz
The OIIO download hash was changed under our feet for the exact same OpenImageIO version.
Successfully built tested on Mac OS

Fix OIIO download hash

---

cmake/dependencies/CMakeLists.txt
cmake/dependencies/dav1d.cmake
cmake/dependencies/ffmpeg.cmake
cmake/dependencies/openssl.cmake

There was a need to allow further FFmpeg customization for super projects, that is for projects consuming Open RV as a sub module.
This commits adds further FFmpeg customization support to Open RV for super projects, that is for projects consuming Open RV as a sub module.
1. New CMAKE cache internal variables have been added to decouple some FFmpeg customizations from FFmpeg so that FFMpeg does not have to know on which targets it depends: RV_FFMPEG_DEPENDS, RV_FFMPEG_EXTRA_C_OPTIONS, RV_FFMPEG_EXTRA_LIBPATH_OPTIONS, RV_FFMPEG_EXTERNAL_LIBS. Example: The RV_DEPS_DAV1D target can now add itself to the FFmpeg dependencies via the RV_FFMPEG_DEPENDS variable. 
2.  The new CMAKE cache internal variable CRV_FFMPEG_CONFIG_OPTIONS can be used by super projects to configure FFmpeg to its liking. …

Add FFmpeg customization support

---

cmake/dependencies/openexr.cmake
cmake/dependencies/patch/openexr_invalid_to_black.patch

This branch add a patch to OpenEXR after we download it.  The patch will fill any scanlines or tiles that it fails to read with black.
This was a feature that was lost when migrating from RV to OpenRV.  During the migration dependencies were removed directly from the repo and instead fetched via CMake's `ExternalProject_Add` functionality.  However, when replacing the OpenEXR code we were not aware it had been modified. 
The correct fix for this is to do it in the API directly (or use OIIO to read OpenEXR which already does exactly that). But until that can be done, we'll just take the changes from the old system and create a patch file from them which can be integrated into CMake's `PATCH_COMMAND` step with `ExternalProject_Add.
Mac M1 Ventura 13.1

Create OpenEXR patch to fill invalid lines and tiles with black

---

src/lib/ip/IPBaseNodes/FileSourceIPNode.cpp

Fix reading movieprocs
This is a followup to https://github.com/AcademySoftwareFoundation/OpenRV/pull/281 which introduced a change to bail out from reading files early when they could not be opened.
This causes a problem with movieprocs (generated sources, blank, etc) which are seen as files whose special syntax are parsed by the MovieProcedural handler after we check this file.  The fix is to simply not perform any checking on the files when it has the 'movieproc" extension.

Fix reading movieprocs

---

CMakeLists.txt
README.md
cmake/dependencies/boost.cmake
cmake/dependencies/python3.cmake
rvcmds.sh
src/bin/python/py-interp/main.cpp
src/build/make_pyside.py
src/build/utils.py

N/A
Merging VFX2023 to main and adding a commit for fixing py-interp
RV is updating their third-party toolchains
Mac, Windows and Linux Rocky 8 and Rocky 9
- Added a commit to fix py-interp: removing Py_Initialize as it is called by Py_Main. Removing PySys_SetArgvEx as it doesn't work when removing Py_Initialize but the new PyConfig works to set Py[...]SetArgv.

VFX2023 merge to main

---

rvcmds.sh

N/A
It uses python to get the current core count to decide how many build tasks should run in parallel.
As for the other variables, someone can set RV_BUILD_PARALLELISM before loading rvcmds.sh to override the value.
The previous number was hardcoded to 8. On my computer, the number should be 10 (M1 Pro). It allows us to build slightly faster by allowing 25% more parallelism. 
Tested on MacOS.
N/A
```
$ source rvcmds.sh
Please ensure you have installed any required dependencies from doc/build_system/config_[os]
CMake parameters:
RV_BUILD_PARALLELISM is 10
RV_HOME is /Users/geffrak/code/git/github.com/org-geffrak/OpenRV
RV_BUILD is /Users/geffrak/code/git/github.com/org-geffrak/OpenRV/_build
RV_INST is /Users/geffrak/code/git/github.com/org-geffrak/OpenRV/_install
CMAKE_GENERATOR is Ninja …
```

Use all cpu cores when building OpenRV

---

docs/build_system/config_windows.md
src/build/make_pyside.py

Updating install Visual Studio instructions to build on Windows
Documentation points to VS2019 & 2017.
Build machines: RHEL7 and Rocky9, Windows, Mac
- Make_pyside: removing source call to 2022 since only 2022 needs to be installed on build machines.

VFX2023: Updating the documentation

---

cmake/install/pre_install_darwin.cmake
src/build/remove_absolute_rpath.py

N/A
When running the install step, make sure that there's no dependencies to files in the build directory. 
Fixes io_oiio.dylib (and libOpenImageIO.2.4.6.dylib), which contained hardcoded full paths to 
files in the build RV_DEPS area. 
Tested on MacOS, where I built stuff using Autodesk's CI, tested on my MacBook running Sonoma.
N/A
```
$ otool -L RV/RV.app/Contents/PlugIns/ImageFormats/io_oiio.dylib 
RV/RV.app/Contents/PlugIns/ImageFormats/io_oiio.dylib:
@rpath/io_oiio.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/libTwkFB.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/libOpenEXR-3_1.30.dylib (compatibility version 30.0.0, current version 30.7.1)
@rpath/libIex-3_1.30.dylib (compatibility version 30.0.0, current version 30.7.1) …
```

MacOS: Fix path to shared libraries from binary dependency list on install

---

docs/rv-manuals/rv-user-manual/rv-user-manual-chapter-thirteen.md

None.
Documentation erroneously stated in [chapter thirteen of the user manual](https://aswf-openrv.readthedocs.io/en/latest/rv-manuals/rv-user-manual/rv-user-manual-chapter-thirteen.html#streaming-movie-media-from-online-sources) that HTTPS in media paths was only supported on macOS. This is wrong, since Linux and Windows also support this.
Also took care of some markdown and other formatting issues.
Improve documentation accuracy.

Fix “Streaming” Movie Media from Online Sources documentation

---

cmake/dependencies/glew.cmake

N/A
Updates GLEW to the last commit, so it can build again.
OpenRV cannot build because GLEW cannot build anymore. GLEW always pull the latest of the OpenGL registries, even if the parser is not ready. 
See https://github.com/nigels-com/glew/issues/399, caused by https://github.com/KhronosGroup/OpenGL-Registry/pull/591.
There's another PR open discussing pinning the registries so OpenRV's build doesn't get another curve ball from a dependency, see https://github.com/nigels-com/glew/pull/400
[x] Tested that it can build on Rocky8
[ ] Tested that it can build on the other platforms
By doing this change, also updated GLEW to the latest. It's mandatory to have a working build, but other things might break.
N/A

Fix the OpenRV build

---

cmake/dependencies/openssl.cmake

NA
Named the OpenSSL's _crypto_lib_name+_ssl_lib_name on all Linux just like RHEL8 and RHEL9: libcrypto.so.1.1
On CentOS 7, OpenSSL was always rebuilt no matter what because of that incorrect _crypto_lib_name+_ssl_lib_name
Test build on both my own CentOS 7 system and the Autodesk internal Jenkins

Fix OpenSSL always rebuilding on CentOS 7

---

src/plugins/rv-packages/window_title/window_title.mu

n/a
Based on the CMake's variable `RV_RELEASE_DESCRIPTION`, add a tag to the window title to identify if the current build is not a release build.
Display that the current build is not a release build in the window title.
Tested on Windows and Linux
n/a
**_Without setting RV_RELEASE_DESCRIPTION or RV_RELEASE_DESCRIPTION=RELEASE (no file loaded)_**
**_Without setting RV_RELEASE_DESCRIPTION or RV_RELEASE_DESCRIPTION=RELEASE (with a file loaded)_**
_**RV_RELEASE_DESCRIPTION=PRE-RELEASE (no file loaded)**_
_**RV_RELEASE_DESCRIPTION="Internal Beta" (with a file loaded)**_

Add a tag in the window title when not in release

---

src/lib/ip/IPCore/IPImage.cpp
src/lib/ip/IPCore/RenderQuery.cpp

NA
Note that this issue was fixed and released in commercial RV 2023.0.2.
It was even successfully validated by the user who reported this issue.
It was missing from Open RV. This PR makes sure to include it.
An RV user reported that the Color Inspector (F5) was not showing with large images when in RV_SOURCE_TILING was enabled.
What we mean by large: The large sample image that the RV user provided us was 2000x200000 (notice the large vertical size).
When RV_SOURCE_TILING is NOT enabled (the default), then the rendering of such a large image is done in one GPU tile and the GPU has a maximum texture size which is typically 16384 for modern GPUs. Which means that the rendering of such a large image is scaled down to fit into the maximum GPU texture size which means that we lose precision …

Fix Color Inspector on large images with RV_SOURCE_TILING

---

src/lib/app/RvApp/RvNodeDefinitions.cpp
src/lib/ip/OCIONodes/CMakeLists.txt
src/lib/ip/OCIONodes/ConfigIOProxy.cpp
src/lib/ip/OCIONodes/OCIOIPNode.cpp
src/lib/ip/OCIONodes/OCIONodes/ConfigIOProxy.h
src/lib/ip/OCIONodes/OCIONodes/OCIOIPNode.h

NA
A little bit of context is required here: missing until this commit in Open RV, the commercial version of RV had two special color management related nodes that some users were leveraging:
1. SYNLinearize: this node could be used to include some media file's embedded color transforms into RV's color management pipeline.
2. SYNDisplay: this node could be used to include an ICC monitor profile file into RV's color management pipeline.
However, these two nodes were implemented using an Autodesk's internally developed color management library.
With the aim of adding these two nodes to Open RV without having to open source this internally developed library, it was decided to replace their implementation with OCIOv2.
This is exactly what this commit contains.
Note that with the aim of …

Add two color mgmt nodes to Open RV that used to be only available in RV

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp

NA
Note that this issue was fixed and released in commercial RV 2023.0.1 and RV 2022.3.3.
It was even successfully validated by the user who reported this issue.
It was missing from Open RV. This PR makes sure to include it.
An RV user recently changed their workflow to use .mxf containers instead of .mov and they were observing that loading say 200x .mxf files takes 2x-3x the time it took them to load 200x .mov files with pretty much the same content (DNXHD).
I used XCode/Instruments to see if I couldn't find any obvious bottleneck and I was able to find that the extra time was spent trying to load the COLR MP4 atom in an .mxf file which is NOT an MP4 file using the MP4V2 Open Source MP4 utility library.
So the extra time was spent scanning the whole file and asserting that the COLR MP4 …

Fix Adding MXF files is slower than MOV

---

src/lib/app/RvCommon/RvPreferences.cpp

[GradientBW_10bit.dpx.zip](https://github.com/AcademySoftwareFoundation/OpenRV/files/13746108/GradientBW_10bit.dpx.zip)
NA
13 years ago, the 10 bits Rendering/DisplayOutputFormat option had blocked on Mac only in the RV Prefs
There is no reason for blocking the 10 bits rendering option anymore.
I was able to successfully exercise the 10 bits rendering on a Mac without any issue. 
This change is safe: Note that the 10 bits rendering display output format is NOT the default display output format so the current commit will NOT impact the behaviour of existing clients.
Now leaving the 10 bits rendering display output option on Mac just like on Windows+Linux.
I was able to successfully exercise the 10 bits rendering on a Mac without any issue.
I used the gradient file in attachment and with …

Unblock 10 bits Rendering/DisplayOutputFormat option on Mac

---

cmake/dependencies/boost.cmake

Now using an alternative location for the boost sources: https://archives.boost.io/release/1.80.0/source/
NA
Now using an alternative location for the boost sources: https://archives.boost.io/release/1.80.0/source/
Note that even though it is taken from a different location, it has the exact same MD5 checksum.
Since a week ago, the boost sources are no longer available from the expected location: https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz
There is an open, still unresolved, issue about this in the boost project:
https://github.com/boostorg/boost/issues/842
This causes a build break when building RV from scratch if one does not have the boost already downloaded.
Successfully tested build on Mac.
Plus the URL checksum matches the one from the …

Fix boost currently unavailable on boostorg.jfrog.io issue

---

rvcmds.sh

#355 
Fixes the path to the default Qt 5.15.2 location on Windows.
The path is invalid, there's an extra Qt folder that is not there by default.
Windows.
N/A
N/A

Fixes the default path to Qt on Windows

---

cmake/macros/rv_stage.cmake
src/lib/app/mu_rvui/CMakeLists.txt
src/lib/app/mu_rvui/rvui.mu
src/plugins/rv-packages/openrv_help_menu/CMakeLists.txt
src/plugins/rv-packages/openrv_help_menu/PACKAGE
src/plugins/rv-packages/openrv_help_menu/openrv_help_menu_mode.mu

NA
This commit's intent is to allow third party applications consuming Open RV as a submodule to customize the Help menu to their liking.
1. The Help menu has been transformed into a package with the exact same content as before.
2. Additionally, a new simple capability to the RV_STAGE(TYPE "RVPKG") macro has been added to prevent an Open RV default package from being installed : RVPKG_DO_NOT_INSTALL_LIST. By appending a package name to this list, one can prevent Open RV from installing the specified package(s).
Tested on Mac.

Enable Help Menu customization

---

src/lib/app/QTBundle/QTBundle.cpp

NA
Prevent missing etc directory warning on launch since the etc directory is optional.
The app/etc directory is optional and is not populated on all platforms like on Linux for example.
Successfully tested on Linux CentOS 7.

Prevent missing etc directory warning

---

docs/rv-manuals/rv-user-manual/rv-user-manual-chapter-three.md

Add some information about the RV logger:
- Where the log files are stored
- What envars are available
With the now implemented logger, the documentation was missing information about where the logs are stored, and how to control the logger with envars. This PR solves this issues.

add log file locations and information about envars

---

CMakeLists.txt

Bump the version of OpenRV to 2.0.0

Set OpenRV to 2.0.0 (2024)

---

src/lib/ip/IPBaseNodes/SwitchIPNode.cpp

NA
Bringing a fix to Open RV which was originally done in RV 2023.0.1 but which was not copied over to Open RV unfortunately. My bad.
Note that this fix is in fact reverting a fix that was done in RV 2023.0.0.
(OTIO : Zooming out of the default output bounds does not reveal media.)
The problem with the fix we did in RV 2023 on SwitchIPNode is that we cannot always prevent RV from using intermediate render. Which is why it needs to be reverted and another solution needs to be applied to solve the original OTIO issue.
Validated the fix on Mac and built successfully on all platforms

Fix potential RV crash when using wipes on Default Stack

---

src/plugins/rv-packages/media_library_demo/media_library_event_plugin.py

NA
Make the media_library_demo.media_library_event_plugin load without error when run from rvio (which does not support modes)
rvio was reporting the following non fatal error:
```
Failed to load media_library_demo.media_library_event_plugin
...
ModuleNotFoundError: No module named 'rv.commands'
```
Successfully built and tested on Mac. 
This fix is not OS specific.

Fix rvio media_library_event_plugin related error

---

src/lib/ip/OCIONodes/OCIO1DLUT.cpp
src/lib/ip/OCIONodes/OCIO3DLUT.cpp
src/lib/ip/OCIONodes/OCIOIPNode.cpp
src/lib/ip/OCIONodes/OCIOLUT.cpp
src/lib/ip/OCIONodes/OCIONodes/OCIO1DLUT.h
src/lib/ip/OCIONodes/OCIONodes/OCIO3DLUT.h
src/lib/ip/OCIONodes/OCIONodes/OCIOIPNode.h
src/lib/ip/OCIONodes/OCIONodes/OCIOLUT.h

Fixes #365
Even though Open RV was recently upgraded to OCIOv2, it was only using the legacy GPU processor implementation of OCIOv2 which is less accurate and more limited than the new OCIOv2 GPU processor implementation. 
This commit leverages the new OCIOv2 GPU processor implementation in Open RV.
Prior to this commit, only the legacy OCIOv2 GPU processor was used (OCIO::getOptimizedLegacyGPUProcessor).
In this commit, the new OCIOv2 GPU processor implementation is now used by default.
With the aim of maintaining backward compatibility of results, I have added a new environment variable which can be optionally defined to tell OCIO to use the legacy GPU processor implementation: 
`export RV_OCIO_USE_LEGACY_GPU_PROCESSOR=1`
The main change is that we are now calling …

Leverage new OCIOv2 GPU Processor

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp

Fixes #404 
Playback performances of Apple Pro Res media is negatively impacted when increasing the the number of reader threads
A check was made in the FFmpeg decoding operation executed by a reader thread (MovieFFMpegReader) to limit the number of seekToFrame() for inter-frame codecs. To detect an inter-frame codec, the code was relying on the FFmpeg's AVCodecContext->gop_size where 0 meant intra-frame only codec. However it turns out that we cannot blindly rely on AVCodecContext->gop_size because it is initialized by default by FFmpeg with a default value of 12 even for intra-frame compression codecs (such as Apple Pro Res for example). 
This resulted in each reader thread decoding extra frames it didn't need to reach the one it needed to decode. 
The result was correct but the amount …

Fix Apple Pro Res playback performance issue

---

src/bin/imgtools/rvio/main.cpp
src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp

NA
RVIO exported movies had a slightly higher frame rate than expected.
Note that one can export a movie either by calling the RVIO command line tool directly or by selecting the File/Export/QuicktimeMovie menu in RV.
This issue was introduced when FFmpeg was updated from 4.2.1 (RV 2023) to FFmpeg 4.4.3 (RV 2024 and Open RV).
After investigation, the slightly higher frame rate was introduced by an incorrect duration stored in the movie file header. This incorrect duration was 1 frame less than the expected duration. Which led to a higher frame rate because the same number of frame was now for a lower duration.
frame rate = numberOfFrames/Duration.
Example with a 10 secs clip at 24 fps:
frame rate = (10 * 24 frames)/(10secs - 1/24 secs) = 24.1 fps
The incorrect clip duration in the movie …

Fix Frame Rate of RVIO's exported movies

---

src/lib/ip/OCIONodes/OCIO1DLUT.cpp

Fixes #412
Fix OCIOv2 build break when RV_VFX_PLATFORM=CY2024
The OCIO::GpuShaderDesc::getTexture() function signature changes in OCIOv2 2.3.x.
Note that OCIOv2 2.3.x is not used by default. It is only used when RV_VFX_PLATFORM=CY2024 because the VFX Platform CY2024 is a work in progress.
There is an extra OCIO::GpuShaderDesc::TextureDimensions parameter that is returned.
We do not need it so this is why I have prefixed it with an underscore to mimic the python convention of unused variables.
Successfully built on Mac + Windows

Fix OCIOv2 build break when RV_VFX_PLATFORM=CY2024

---

src/lib/app/RvCommon/QTGLVideoDevice.cpp

Fixes #433
Make sure that the QGLWidget gets redrawn by updateGL() even when completely overlapped by another window.
On macOS, Qt correctly detects when the QGLWidget is completely overlapped by another window and in which case resets the Qt::WA_Mapped attribute. This prevents the GLView::paintGL() operation from being called by m_view->updateGL(), which will result in automatically interrupting any video playback that might be in progress while the RV window is completely overlapped.
This is an undesirable behaviour during a review session, especially if an external video output device is used.
Tested on macOS Sonoma 14.0

433: Fix Playback stopping when RV is completely overlapped on macOS

---

src/lib/app/TwkApp/TwkApp/VideoDevice.h
src/lib/app/TwkApp/VideoDevice.cpp
src/lib/graphics/TwkGLF/GLVideoDevice.cpp
src/lib/image/TwkFB/FastConversion.cpp
src/lib/image/TwkFB/TwkFB/FastConversion.h

NA
This commit adds P216 video output buffer format support to Open RV.
P216 
This is a 4:2:2 buffer in semi-planar format with full 16bpp color
precision. This is formed from two buffers in memory, the first is a 16bpp
luminance buffer and the second is a buffer of U,V pairs in memory. 
This format is the 16 bits internal buffer format representation used by the NDI SDK which will allow an upcoming version of Open RV to support the NDI SDK 6.0.0 with 10 bits support.
Tested on macOS

Add P216 video output buffer format

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp
src/lib/image/MovieFFMpeg/MovieFFMpeg/MovieFFMpeg.h

#388
Fixed issue with addTrack method, added back some code to fix a crash when exporting and added back some code to fix a infinite loop while decoding audio.
FFmpeg 6 update
n/a
n/a

[FFmpeg 6 Update] Fix issues by adding missing code

---

cmake/dependencies/ocio.cmake
cmake/dependencies/openssl.cmake
cmake/dependencies/pcre2.cmake
cmake/dependencies/python3.cmake
src/build/make_python.py

n/a
Long standing instability with OTIO in debug on Windows. I always had issues building OpenRV in debug on Windows due to OTIO. This PR makes the debug build more stable, and I can build OpenRV in debug straight from a fresh cloned repository.
n/a
n/a

Fix issue with OTIO in debug on Windows

---

src/lib/geometry/TwkPaint/Path.cpp
src/lib/geometry/TwkPaint/TwkPaint/Path.h

This fixes an issue when using the annotation tools and having strokes with variable widths.
Variable widths happen when you use a stylus/wacom tablet with pen pressure. When widths can vary, it is possible for the widths of the stroke be just right so that the extruded edges become nearly parallel. This case currently isn't being handled. This creates "spikes" on your brush stroke that can seemly appear at random.
https://github.com/AcademySoftwareFoundation/OpenRV/assets/814966/b7f1dd3f-1eee-4d62-97ec-add94ac12e11
Here is a minimal isolated case of the issue happening [spike_isolated.rv.](https://github.com/AcademySoftwareFoundation/OpenRV/files/14950061/spike_isolated.rv.zip)
I also graphed the polygons in desmos so its easier to see
https://www.desmos.com/calculator/gxmkrpdr2o
The …

RVPaint fix segment edge intersection when path has variable widths

---

cmake/dependencies/boost.cmake
cmake/dependencies/zlib.cmake
docs/build_system/config_macos.md
rvcmds.sh
src/build/make_pyside.py
src/lib/geometry/TwkPaint/Path.cpp
src/lib/geometry/TwkPaint/TwkPaint/Path.h

Fixes #278
OpenRV will now default to using Boost 1.81 if the user has Xcode 15 or greater. Otherwise, OpenRV will default to using Boost 1.80, which is compliant with CY 2023 and works with Xcode 14.3.1. This also is outlined for the user in changes to documentation. 
Xcode 14.3.1 is deprecated on macOS Sonoma in favour of Xcode 15 and up, which means users on Sonoma or later will not be able to build OpenRV without this change.
A complete build of OpenRV using `rvbootstrap` on macOS Sonoma and Xcode 15.

Make OpenRV buildable on Xcode 15

---

src/lib/ip/OCIONodes/OCIOIPNode.cpp

Should fix [#463](https://github.com/AcademySoftwareFoundation/OpenRV/issues/463)
Added "lock" variable name to all anonymous QMutexLocker instances to extend their lifespan to the end of their scope. This matches the QMutexLocker usage in other parts of the app (RVConsoleWindow.cpp and QTAudioRenderer.cpp).
Enabling OCIO was causing frequent crashing when reader threads were set greater than 1, in particular under MacOS Sonoma.

463: Unanonymised QMutexLocker usage in OCIOIPNode.cpp

---

README.md
docs/build_system/config_linux_rocky9.md

NA
Remove unnecessary cmake build from rocky9 build system setup
Rocky Linux 9 comes with cmake version 3.26.5 which is more recent than the cmake version 3.24 built from sources that were in the build system setup instructions.
Open RV Rocky 9 build system instructions were validated on a branch new Rocky 9 installation.

Remove unnecessary cmake build from rocky9 setup

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp

Fixes #483
No longer using the MovieFFMpeg global context pool (since FFmpeg 6.0)
Rationale: The global context pool was based on the premise that a context could be opened and closed multiple times. 
However, with FFmpeg 6.0, this premise is no longer valid and was causing crashes.
As per the FFmpeg 6 documentation: https://ffmpeg.org/doxygen/trunk/deprecated.html:
"Opening and closing a codec context multiple times is not supported anymore – use multiple codec contexts instead."
Successfully validated repro steps

Fix FFmpeg 6.0 crashes when loading 50+ clips and stressing the timeline

---

src/bin/apps/rvpkg/main.cpp
src/lib/app/RvCommon/RvPreferences.cpp
src/lib/app/RvPackage/PackageManager.cpp
src/lib/app/RvPackage/RvPackage/PackageManager.h

Users can now upload multiple packages at the same time through a compressed zip file using the extension **.rvpkgs**. These **.rvpkgs** files can be uploaded using the `rvpkg -add ...` command in the shell, or directly in the UI under the `Preferences/Packages` section of the menu.
In either case, **.rvpkgs** files will be immediately unzipped into the packages they contain before each package is added to OpenRV. 
Users can also add and install these **.rvpkgs** bundles using a chain command as follows.
`rvpkg -force -install -add <destination> <location of .rvpkgs file>`
This change was tested on MacOS. To replicate the test, recreate the following steps.
**Creating an .rvpkgs file**
1. Find the .rvpkg files you want to bundle
2. Create a zip folder containing these .rvpkg files
3. …

Add .rvpkg bundle support for rvpkg command line tools and UI

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp

Added an additional check to another metadata field when loading movie clips to ensure that rotation metadata is captured correctly.
In FFmpeg 6.0, rotation metadata can be loaded incorrectly without this check.
macOS Sonoma 14.5
- Added an additional check to the `side_data` field when movies are loaded in to RV
- Covered additional cases of negative rotation metadata, as this was not covered already

Fix rotation metadata loading incorrectly with FFMPEG 6

---

rvcmds.sh

#502 
When RV is built, we now search for QT_HOME (the QT installation location), rather than assuming it. 
Some customers have reported having issues with QT_HOME not being set correctly due to the static assumption we have made about the installation location of QT.
QT_HOME is set properly, regardless of QT installation location, for macOS Sonoma 14.5 and Windows 11. L

Automatically set QT_HOME variable if it is not already set

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp

KV in particular allows arbitrary key/value metadata pairs. The previous code only allowed a known list of parameters to be passed through to RV. This version has a list of parameters that should NOT be passed through.
Describe what you have tested and on which operating system.
I've tested loading mov and mkv files on windows.
Below is an example of getting a field called "samfield" to show up in the info display.
This metadata was added using the following ffmpeg command:
```
ffmpeg -i chimera_cars_srgb-test_mov-mjpeg.mov -metadata samfield=samtest -c copy chimera_cars_srgb-test_mov-mjpeg.mkv
```

Modified to allow arbitrary metadata to show up in RV (v2)

---

README.md
cmake/dependencies/ffmpeg.cmake

NA
Make FFmpeg rebuild when configure options change
Also fixed an inconsistency with the RV_FFMPEG_NON_FREE_DECODERS_TO_ENABLE documentation in README.md.
In a previous commit was added the capability of adding non free FFmpeg decoders+encoders at configure time.
However, there were 2 issues when re-configuring with different non free codec options after a build: the FFmpeg was not rebuilt, and if it was rebuilt, the new FFmpeg libs were not copied over the stage area.
Both of these issues are solved in this commit.
Also in this commit: An inconsistency with the RV_FFMPEG_NON_FREE_DECODERS_TO_ENABLE/RV_FFMPEG_NON_FREE_ENCODERS_TO_ENABLE documentation in README.md was fixed. (The README.md was incorrectly documenting the previous names of the FFmpeg configure options.)
Successfully tested …

Make FFmpeg rebuild when configure options change

---

docs/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-fifteen.md
docs/rv-manuals/rv-user-manual/rv-user-manual-chapter-three.md

NA
Fix incorrect documentation with respect to the Open RV preferencess and log location.
The documentation for the Open RV preferences and log file locations was incorrectly referencing Autodesk.
It is actually under ASWF (Academy Software Foundation)

Fix doc wrt Open RV prefs and log location

---

CMakeLists.txt

NA
Set OpenRV version to 2.1.0
This is to be able to set a minimal version baseline for upcoming support of Flow Production Tracking packages in Open RV.

Set OpenRV version to 2.1.0

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp

I noticed that if you have an AV1 file, you need to set the threads to 1, to playback properly without stuttering.
e.g. compare:
rv.exe -debug playback -fps 30 -playMode 2 chimera_cars_srgb-test_mp4-libsvtav1-10bit.mp4 -rthreads 4 -play
to
rv.exe -debug playback -fps 30 -playMode 2 chimera_cars_srgb-test_mp4-libsvtav1-10bit.mp4 -rthreads 1 -play
It seems like av1 is missing from the slowRandomAccessCodecsArray array.
Changing this seems to improve things. Athough with the above debug enabled, I'm still seeing lines like:
PATTERN FAIL #15 :  3 1 2 2 2 2 3 2 1 2 // frame = 83 (83)
PATTERN FAIL #16 :  2 3 1 2 2 2 2 3 2 1 // frame = 84 (84)
Which I'm guessing is not good. But that might be something else.

AV1 codec shouldnt have threaded readers.

---

src/lib/app/RvCommon/RvApplication.cpp
src/lib/app/RvCommon/RvPreferences.cpp
src/lib/app/RvCommon/RvTopViewToolBar.cpp
src/lib/app/TwkApp/Application.cpp
src/lib/app/TwkApp/TwkApp/Application.h
src/lib/ip/IPCore/IPCore/Application.h
src/lib/ip/IPCore/IPCore/IPGraph.h
src/lib/ip/IPCore/IPGraph.cpp

NA
This commit makes sure that the allocated video modules are released when RV exits.
To do so, the TwkApp::VideoModules container which previously contained raw pointers (std::vector<VideoModule*>) which were never released on exit, has been converted to std::vector<std::shared_ptr<VideoModule>>
This missing TwkApp::VideoModules cleanup on exit, was causing a crash on Windows when the upcoming NDI video output plugin was unloaded. 
More specifically: The NDI crash was caused when trying to unload the NDI dll without having called the NDIlib_destroy().
Note that NDIlib_initialize() is called when allocating an NDI video module while  the NDIlib_destroy() is called when releasing the NDI video module. So it became essential to fix this TwkApp::VideoModules  cleanup on exit to prevent a …

Fix Windows crash on exit with upcoming NDI video output plugin

---

src/build/requirements.txt

Fixes #511
Force the previous version of OpenTimelineIO to be used in Open RV (==0.16.0) to fix the crash at launch.
Open RV crashes on launch on Windows since the OpenTimelineIO python package was updated to 0.17.0
This started to occur on July 2nd, 2024. Matching the release of OpenTimelineIO version 0.17.0
Work around:
./py-interp -m pip install OpenTimelineIO==0.16
The latest version of OpenTimelineIO is normally used in Open RV, but the recently released version is causing a crash at startup. 
As an emergency fix, we will therefore force the previous version of OpenTimelineIO to be used in Open RV (==0.16.0) to fix the crash at launch until this OpenTimelineIO issue is resolved at the source.
Successfully tested on Windows 11 and macOS.

Fix OpenTimelineIO crash at startup

---

README.md
THIRD-PARTY.md
cmake/macros/FindNDI_SDK.cmake
src/build/requirements.txt
src/plugins/CMakeLists.txt
src/plugins/output/CMakeLists.txt
src/plugins/output/NDI/CMakeLists.txt
src/plugins/output/NDI/NDI/NDIModule.h
src/plugins/output/NDI/NDI/NDIVideoDevice.h
src/plugins/output/NDI/NDIModule.cpp
src/plugins/output/NDI/NDIOutput.cpp
src/plugins/output/NDI/NDIVideoDevice.cpp

Fixes #363
This commit adds an optional NDI&reg; Video Output plugin to Open RV.
Note that The NDI&reg; SDK is NOT provided by Open RV. It can be optionally downloaded from https://ndi.video/ and installed after agreeing to its license agreement.
Please refer to the NDI&reg; SDK license agreement.
To add the NDI&reg; Video Output capability to Open RV as requested by many Open RV users.
Successfully validated on macOS, Windows 11, Rocky Linux 9 using the latest NDI&reg; SDK.

Add NDI Video Output plugin to Open RV (Optional)

---

cmake/dependencies/boost.cmake

n/a
Make sure that LZMA is disabled when building Boost because OpenRV is not using it.
There is a quotation issue with how we use the NO_LZMA option for boost where it does not really disable it. 
This cause issue when OpenRV finds a LZMA that was compiled for x86_64 architecture.
Tested the build on  Windows, Rocky Linux 8/9, MacOS Intel and ARM64.

Make sure that LZMA is disabled when building Boost (MacOS)

---

src/lib/app/RvCommon/RvApplication.cpp

N/A
Add a simple environment variable check to see if the user would like to load video output plugins.
These are heavy plugins and actually slow dow the time it takes for RV to boot. If the user so chooses, they should have the option to disable them from being loaded.
Tested on MacOS 14.5, disabling these plugins increased loading speed by about 20% when opening a piece of media with Open RV/

Add environment variable that allows users to disable loading video output plugins

---

src/build/remove_absolute_rpath.py

n/a
Fix an issue during the install step where it tries to delete a RPATH multiple time due to a universal library.
Keep a list of deleted rpath for a specific file and do not delete the same RPATH multiple time.
Install step was failing on MacOS ARM64

Fix issue install step tries to delete rpath multiple times (MacOS ARM64)

---

src/lib/app/TwkApp/Bundle.cpp

N/A
Based on this review: https://github.com/AcademySoftwareFoundation/OpenRV/pull/530#discussion_r1714530682
Include statement in `src/lib/app/TwkApp/Bundle.cpp` has been fixed.
The include statement was trying to include a file that dosen't exist, `file.h` instead of `File.h`.
Builds correctly on...
- MacOS 14.5 Sonoma

Fix typo to include File.h in Bundle.cpp

---

README.md
docs/build_system/config_macos.md

NA
Update macOS build setup to allow Terminal to update or delete other applications
Now required starting with macOS 14.5

Update macOS build setup doc to allow Terminal to update other apps

---

cmake/dependencies/dav1d.cmake

Update the version library from 1.0.0 to 1.4.3.
Sam Richards (Disney) asked at the last Open RV TSC if we could update the libdav1d component from 1.0 to latest 1.4.3 which has better performances according to him.
The build step has been tested on all three platforms.

Update dav1d version to 1.4.3

---

Notice.txt

The libDevil mention is no longer required in Notice.txt since the library has been removed [here](https://github.com/AcademySoftwareFoundation/OpenRV/pull/550).

Remove libDevil from Notice.txt

---

.gitignore
README.md
docs/build_system/config_macos.md
rvcmds.sh

N/A
The Python version included with MacOS Sonoma 14.5 adopted [PEP 668](https://peps.python.org/pep-0668/), which is meant to prevent conflicts between system level Python packages with project specific Python packages, like what is included in `requirements.txt`. 
This means that the user will encounter an error when attempting to install Python requirements unless they use the tag `--break-system-packages` tag. By using a virtual environment, system-level conflicts are avoided and the user has a safer build of Open RV. 
Mac OS Sonoma 14.5 and Windows 11.
PEP 668 error without a virtual environment, triggered by running `rvbuild`.

Create Python virtual environment when Open RV/RV is being built

---

rvcmds.sh

n/a
Create a debug folder when building in debug. (`_build_debug` vs `_build`)
It can cause problem if someone switch between built type (having mixed of debug and release).

Create a different build folder for debug

---

.github/workflows/ci.yml

n/a
Prevent the run of workflow is the repository owner is not ASWF. The new if conditon should prevent the workflow to be schedule and run on forks.
The schedule workflow is executing in forks as well.
n/a

Prevent the schedule workflow from running in fork

---

cmake/dependencies/CMakeLists.txt
cmake/dependencies/expat.cmake
cmake/dependencies/ocio.cmake

n/a
Remove `vcpkg.cmake` and add an `expat.cmake` to build Expat for OCIO
By adding `expat.cmake,` it respect the same build structure as the other dependencies.
Windows

Remove vcpkg.cmake and add expat.cmake for OCIO (Windows Only)

---

requirements.txt

Set `pyzstd` and `py7zr` to the maximum version working with Python 3.8.
The version of `pyzstd` required by the latest version of `py7zr` doesn't work with Python 3.8 which is used with CentOS 7 which is causing a build break. This fix should be removed once the support for CentOS is dropped.
The build step was tested on CentOS 7.

Fix build break on CentOS

---

cmake/dependencies/bmd.cmake

Fixes #604
Added a post-install step in the BlackMagicDevice cmake file (bmd.cmake) to generate the DeckLinkAPI.h header file via midl.exe which is required to build the Blackmagic Video Output plugin on Windows.
Note that the BlackMagic SDK only provides .idl files on Windows (not .h header files). Since that we are building OpenRV in a non managed way, we need to generate a DesktopLinkAPI.h header file from the provided .idl files.
The Blackmagic Video Output plugin build on Windows was broken.
Successfully tested on Windows.
Note that this commit is Windows specific so it should not impact any other OS.

#604: Fix Blackmagic Video Output plugin build on Windows

---

docs/rv-packages/rv-otio-reader.md
src/plugins/rv-packages/otio_reader/PACKAGE
src/plugins/rv-packages/otio_reader/annotation_schema.py
src/plugins/rv-packages/otio_reader/manifest.json
src/plugins/rv-packages/otio_reader/otio_reader.py
src/plugins/rv-packages/otio_reader/otio_writer.py

The `read_otio_string` function was added to parse the OTIO object containing the timeline sent by the Review App when RV is joining a new session as a participant. Since the timeline contains some annotation fields, the annotation schema was added in order to let OTIO know that it is a known schema during the deserialization step. However, nothing is done with the annotations at this stage.
This is the first step in adding back the new OTIO schema as the preferred way of communication between RV and the Review App.
Live review using the new schema was tested between a local Review App where the feature was enabled with https://creative-collab.dev.shotguncloud.com and RV on MacOS.

Add RV as a participant using the new Live Review schema

---

docs/rv-packages/rv-otio-reader.md
src/lib/app/mu_rvui/extra_commands.mu
src/plugins/rv-packages/otio_reader/PACKAGE
src/plugins/rv-packages/otio_reader/annotation_hook.py
src/plugins/rv-packages/otio_reader/manifest.json
src/plugins/rv-packages/otio_reader/otio_reader.py
src/plugins/rv-packages/otio_reader/paint_schema.py
src/plugins/rv-packages/otio_reader/point_schema.py

A participant to a Live Review session is now able to see annotations drawn by the presenter.
The changes were tested on MacOS arm64.

Add annotation in OTIO reader for Live Review

---

.gitignore
src/lib/ip/IPBaseNodes/FileSourceIPNode.cpp

Fixes #616 
Note: Progressive source loading is NOT enabled by default in Open RV as it significantly complexifies custom scripting since many previously synchronous operations become asynchronous. 
For reference: https://aswf-openrv.readthedocs.io/en/latest/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-two.html#progressive-source-loading
Progressive source loading in RV can be enabled by setting the following environment variable:
`export RV_PROGRESSIVE_SOURCE_LOADING=1`
Open RV sometimes crashes when loading an rv session containing missing media with progressive source loading enabled.
Modifying the RV execution graph that can potentially trigger events to be notified to Mu or Python plugins can only be done in the main thread. When progressive source loading is enabled, …

#616: Fix crash when prog source loading enabled

---

src/plugins/rv-packages/otio_reader/annotation_hook.py

Add a new points to the list of points to draw only if it's not already there.
The number of points was causing the opacity level too be too opaque.
The opacity level was tested by changing it's value in the ReviewApp and seeing the resulting annotation in RV on MacOS.

Fix live review annotation opacity

---

src/lib/app/RvCommon/RvPreferences.cpp

Fixes #620
This commit now enables the user to override the following optional video output related command line options:
- presentVideoFormat
- presentDataFormat
- presentAudio
User cannot override settings presentVideoFormat and presentDataFormat once specified on the command line
Successfully tested on macOS

620: Fix overrides of video output command line options

---

.github/workflows/ci.yml

#590 
Removing MacOS ARM64 CY2023 from the CI because XCode 14 is not available anymore and it is needed to build Qt 5.15.2 from source for ARM64. **The CI for ARM64 will be back with VFX2024.**
At the same time, I've modified the python version to use 3.10 to align with VFX2023.
CI

Remove MacOS ARM64 build from CI and align Python version for CY2023

---

.github/workflows/ci.yml

n/a
Remove the path-ignores in the CI.
It causes issues where the CI is not running but is still mandatory.

CI - Run job on all changes

---

docs/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-two.md

na
The Open RV documentation incorrectly stated that the following command could be executed to enable progressive source loading in Open RV:
`setProgressiveSourceLoading = true`
This was incorrect and fixed in this commit.
Here is the fix marked down preview:
Incorrect documentation

Fix the doc about setProgressiveSourceLoading()

---

src/lib/ip/IPCore/ShaderFunction.cpp

Fixes #457
Prevent shader collisions with 'uniform sampler1D' or 'uniform sampler2D' variables by adding a hash to the
array variable name to make it unique.
This was already done for other kinds of variables but not uniform sampler1D or sampler2D.
This is not an issue with OCIOv2 per say. This is an issue because Open RV combines the results of multiple shaders generated by OCIOv2 so Open RV needs to make the generated global variables unique.
Note that this issue happened with 1D LUTs of 2048 length because OCIOv2 uses different sampler types depending  of the LUT size: a sampler1D for LUTs<=2048 entries, and a sampler2D type for LUTs>2048.
Similar to a previously fixed [issue](https://github.com/AcademySoftwareFoundation/OpenRV/commit/c7d1cd495c0340b1590e02884419f38c7f9c5d6a#diff-1f024a …

457: Fix OCIO failure with 1D LUTs of 2048 length

---

cmake/dependencies/ffmpeg.cmake

n/a
Updated FFmpeg to version n6.1.2 to fix the issue.
Rocky Linux 9 CI is failing.

Update to FFmpeg n6.1.2 to fix an issue with Rocky Linux 9 and vulkan

---

cmake/defaults/rv_targets.cmake

n/a
Add missing compiler definitions for MacOS and Linux. There are some unrelated changes because of the pre-commit hook.
The command build_os and build_architecture were returning empty strings on Linux.
Rocky 8

Fix issue with runtime.build_os and runtime.build_architecture

---

src/bin/imgtools/rvls/CMakeLists.txt
src/bin/imgtools/rvls/main.cpp

Initialized the QCoreApplication on MacOS before creating the bundle.
The QCoreApplication was not being created properly on MacOS.
Successfully tested on MacOS

Fix rvls -x skipping license validation on MacOS

---

src/lib/ip/IPBaseNodes/FileSourceIPNode.cpp
src/lib/ip/IPBaseNodes/IPBaseNodes/FileSourceIPNode.h

Fixes #616
Note: Progressive source loading is NOT enabled by default in Open RV as it significantly complexifies custom scripting since many previously synchronous operations become asynchronous. 
For reference: https://aswf-openrv.readthedocs.io/en/latest/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-two.html#progressive-source-loading
Progressive source loading in RV can be enabled by setting the following environment variable:
`export RV_PROGRESSIVE_SOURCE_LOADING=1`
Open RV sometimes crashes when executing the following script repeatedly:
```python
from rv import commands as rvc
rvc.setProgressiveSourceLoading(True)
srcA = {
"Streaming":
"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
"Frames": …
```

616: Fix MediaLibrary crash when prog source loading enabled

---

src/lib/app/PyTwkApp/PyInterface.cpp

NA
Now pre-initializing the Python interpreter in RV to ensure that the PyConfig.use_environment is set to 1 (default).
Without this pre-initialization, PyConfig.use_environment defaults to 0 which means that the currently set locale gets ignored as well as the PYTHONUTF8 env var if set by the user.
Since commercial RV 2023 (Python 3.9.13), the default Python locale was no longer respecting the currently set environment variables (including the PYTHONUTF8 env var) and the script described below, was always returning:
US-ASCII
0
Prior to this release, such as commercial RV 2022.3.1 (Python 3.7.13), the default Python locale was respecting both the currently set environment variables, including PYTHONUTF8 env var. So we would generally have
UTF-8
1
I used this python script to validate the …

Fix default Python locale and now honor PYTHONUTF8 env var

---

docs/build_system/config_linux_centos7.md
docs/build_system/config_linux_rocky8.md
docs/build_system/config_linux_rocky9.md

NA
Add CMake custom build to the Rocky9 build instructions
A newer version of CMake than the one coming standard with Rocky 9 is required to build an RV dependency.
Validated on Rocky 9

Add CMake custom build to the Rocky9 build instructions

---

src/bin/imgtools/rvls/CMakeLists.txt
src/bin/imgtools/rvls/main.cpp

Initialize Python in rvls main function to match the behaviour of rvio inside the ShotGrid license validation.
The license validation was failing on Linux when using rvls, but the same code was working fine with rvio because of the Python initialization in main(). The Python interpreter from rvio had more capabilities that were needed to properly import Python modules on Linux.
This change was tested on Rocky8, MacOS Sonoma and Windows 11.

Add Python initialization in rvls

---

src/plugins/rv-packages/otio_reader/annotation_hook.py

A default global scale value is calculated based on the aspect ratio of the first source if it couldn't be obtained from the OTIO.
When no `available_image_bounds` is present in the OTIO, no global scale value was being calculated. This was causing an issue where the annotations couldn't be displayed in RV during a Live Review Session.
Successfully test on MacOS

Add default global scale value if missing in the annotation hook

---

.clang-tidy

A .clang-tidy was added at the root of the project to lint our C++ code. We should do the same for commercial RV if everyone is happy with this one. The formatStyle is set to 'file' so that the changes suggested by the linter will match the rules in our .clang-format. WarningAsErrors could be changed to match all or any of the checks if, at one point, we would want to enforce the respect of a category. HeaderFilterRegex could be changed if we need to exclude some header files from being lint by clang-tidy.
Just like we are formatting our code with the .clang-format, we should also lint it using a .clang-tidy. This is the one I've been using personally but I think it could be beneficial to others, especially for code reviews since it would help to avoid having to ask for small changes that …

Add a .clang-tidy to lint the C++ code

---

cmake/dependencies/gc.cmake

NA
Increased the Garbage Collector's maximum number of roots from 2048 to 4096 by enabling the large config option in the garbage collector config.
RV+Open RV could no longer launch since Apple released macOS Sequoia 15.2 (2 days ago).
The following fatal error was reported by the garbage collector component of RV:
"Too many root sets"
Successfully tested on macOS Sequoia 15.2.

Fix Open RV not launching on macOS Sequoia 15.2

---

src/plugins/rv-packages/otio_reader/annotation_hook.py
src/plugins/rv-packages/otio_reader/annotation_schema.py
src/plugins/rv-packages/otio_reader/paint_schema.py
src/plugins/rv-packages/otio_reader/point_schema.py

This PR aims to clean up a bit the code related to the OTIO reader for annotations in Live Review.
I see that some files for other hooks and schemas are in camel case instead of snake case. Does anyone knows if there is a reason? Is everyone ok with me renaming the files inside `otio_reader` to use snake case instead?

Clean up the OTIO reader annotation

---

src/plugins/output/AJADevices/AJAModule.cpp

The GLEW library was not initialized before using other GLEW extension 
The AJA output module was having the same issue as the one mention in the following PR with BlackMagic: [[#116](https://git.autodesk.com/media-and-entertainment/rv/pull/116)](https://git.autodesk.com/media-and-entertainment/rv/pull/116).
Starting the presentation mode on Windows 11 with an AJA Io 4K Plus device does not make RV crash anymore.

Fix AJA not working on Windows

---

src/plugins/python/CMakeLists.txt
src/plugins/python/network/CMakeLists.txt
src/plugins/python/network/__init__.py
src/plugins/python/network/network/__init__.py
src/plugins/python/network/network/addSource.py
src/plugins/python/network/network/muConsole.py
src/plugins/python/network/network/playControl.py
src/plugins/python/network/network/rvNetwork.py

NA
This python module was unfortunately forgotten when RV was open sourced.
I moved the RV network python module files one sub-directory under their current location in order to be able to use the RV_STAGE("PYTHON_SOURCE_MODULE" FILES network_driectory) Cmake macro to install and made the necessary adjustments to the CMake build system to install it when building Open RV.
With this commit, once built, the RV network python module files will be under the 
RV.app/Contents/PlugIns/Python/network directory.
Successfully testes on macOS.

Add missing RV network python module

---

src/lib/mu/MuQt6/QVariantType.cpp
src/lib/mu/MuQt6/handrolled/QVariantDefinitions.cpp
src/lib/mu/MuQt6/handrolled/QVariantSymbols.cpp

n/a
There were some changes in the Qt 6 QVariant type and it seems like we need to explicitly define a QVariant constructor for QIcon in Qt 6.
Mu Command API Browser is not opening in the build using Qt 6.
Rocky 8

Feature/Qt6 - Fix issue where Mu Command API Browser is not opening

---

src/lib/ip/IPBaseNodes/SequenceGroupIPNode.cpp
src/plugins/rv-packages/otio_reader/otio_reader.py

NA
This commit fixes two issues related to the import of media with mixed frame rates.
Note: RV supports only one frame rate per sequence which is dictated by the first source in the sequence.
RV automatically retimes the clips that do not match the frame rate of the first source.
**Issue#1:** 
The first issue is not OTIO specific and is actually a regression that was introduced 5 years ago with the progressive source loading optimizations (even when progressive source loading is not explicitly used.)
The issue is the following:
When adding multiple sources in one addSources() call, then no retiming gets automatically added for the sources that do not match the first source's frame rate. However, when you add the sources sequentially in two addSources() calls then all the sources are …

Fix OTIO import of tracks with mixed frame rates

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp

Fixes #696
The the rvio's 'timecode' option was used, the following error is reported in the console and the timecode option is ignored:
`ERROR: Valid timecode frame rate must be specified. Minimum value is 1`
This is a regression that was introduced when updating RV to FFmpeg 6
Now initializing the required avStream->avg_frame_rate and avCodecContext->framerate which is required in FFmpeg 6 to make the timecode rvio output option.
Note that this commit only impacts the mio_ffmpeg export function. 
Successfully tested on macOS. The issue is not OS specific.

Fix rvio timecode option issue with FFmpeg 6

---

src/lib/ip/IPCore/Session.cpp

NA
**Problem:**
In some situations, invoking the rv.commands.clearSession() would leave with the caching turned off for the remainder of the RV process lifetime which was impacting playback performances for the remainder of the RV process lifetime.
Note that the caching=off would not be persisted. So at the next RV relaunch, the caching would be enabled.
This problem can be reproduced when importing an OTIO into RV.
Before the OTIO import, caching is on:
After the OTIO import, the media caching would be effectively disabled:
**Cause:**
This was caused by the rv.commands.clearSession() which momentarily turn off caching to empty its content.
But the original caching state is never restored until the user relaunches RV.
**Fix:**
Now restoring the original caching state in Session::clear(). …

Fix rv.commands.clearSession() caching issue

---

src/lib/app/mu_rvui/external_qprocess.mu

When exporting (or, for that matter, calling an external process) was finished, the "finish" callback faied and caused RV to crash. 
The fix was simply to add a missing parameter at the end of the signature of the callback method called by connect() when QProcess.finish is called, to match what is expected in Qt6 (and Qt5, actually)
This crash appeared whenever launching an external process, not just rvio. So other issues we found regarding a crash when launching an external process should also be fixed with this change.
Fixes crash at end of export process
Tested on Linux64 Rocky 9.5.
It's not clear why this worked on the Qt5 branch and crashed on Qt6. Indeed, the "finish" signal always took 2 parameters, while the Mu signal only took one.
see below : similar signature of …

Feature/Qt6 - Export dialog will freeze at the end of an export

---

src/plugins/rv-packages/otio_reader/annotation_hook.py
src/plugins/rv-packages/otio_reader/effectHook.py
src/plugins/rv-packages/otio_reader/paint_schema.py

The paint schema was updated to reflect the latest changes done to the Live Review spec, and the annotation hook is now using the `visible` attribute to set the visibility of the annotations based on the OTIO timeline received by the ReviewApp.
During a Live Review session, a presenter can click on a `hide annotations` button to hide all the annotations on all the frames. The PR allows RV to correctly display the annotations as a Live Review participant based on the presenter's choice.
The changes were successfully tested on MacOS.

Handle hide annotations

---

src/lib/app/mu_rvui/HUD.mu

When we clicked or dragged the widget during a quicktime export (or any instance of the ProcessInfo widget for that matter), we (almost) inevitably always crashed. Happened in Qt5 and Qt6 branch, and as far back as RV 2023, apparently. 
When we clicked on the ProcessInfo widget, the code tries to access the _buttons[] array to see if we are clicking in the (X) button, but simply reading this array crashed RV. 
It turns out that for the ProcessInfo widget, the render() method recreated the _buttons[] array, which contained the coordinates and process info for the (X) cancel button. This was in a different thread than the event-handling thread. So, while the render method was executing and the _buttons[] array was being recreated, the event-handling thread was trying to read the same array …

Feature/Qt6 - fix crash when clicking on rvio Export widget while it's exporting quicktime video  (#35176)

---

.github/workflows/ci.yml
src/plugins/rv-packages/otio_reader/otio_reader.py

NA
There were a couple issues associated with multiple media representation support in OTIO reader:
- Local file path could not be used because the server URL was always preprended.
- When creating a video track, its duration was 1 frame too long
- New OTIO based media representation names were inconsistent with the previously named MMR in RV such as 'mp4', 'path_to_movie', and 'path_to_frames'
- Now only prepending the server URL when the target url starts with /file_serve/version
- Fixed the duration in  _set_sequence_edl()
- Renamed known media representation names to standard media rep names used by RV such as Streaming, Movie, and Frames.
Successfully tested on macOS. The fix is not OS specific

Fix MMR support in OTIO reader

---

src/lib/app/RvCommon/RvDocument.cpp

Added a singleshot timer to force a resize event to the main window, in order to fix an image scale issue when first starting RV.
On macOS (and, presumably, any platform that supports HDPI) the initial display of the main view's image will not be scaled properly. After much investigation, this appears to be a Qt bug but were being unable to truly identify the root cause (coordinates are ok, pixel scale is ok, pixel ratio is ok, gl surface is ok, gl viewport is ok, etc etc. 
Oddly enough, the issue disappeared when resizing the view, even 1 pixel, but this has to be done after the view is first shown.
As a result, we dimply decided to force two resize events to occur (+1 pixel, and then -1 pixel). This has no visible effect on startup (or, you'd really need eagle eyes) to go: "A-HA!"
This …

Feature/Qt6 - Fix hdpi issue that magically fixes itself when resizing the main window

---

src/lib/app/RvCommon/GLView.cpp
src/lib/app/RvCommon/RvApplication.cpp
src/lib/app/RvCommon/RvCommon/GLView.h
src/lib/app/mu_rvui/HUD.mu

Fixes #38133
Could not open presentation device after setting Presenation device to NDIDevice, and then doing CTRL-P to enable it.  The error message was due to a ";" at the end of an if-statement, but then it caused opengl errors down the line due to the gl context being invalid after calling swapBuffers.
Turns out all the swapBuffer management is no longer needed with QOpenGLWidget, explanation in the summary below.
Note for Qt6 . QOpenGLWidget implementation:
With the new QOpenGLWidget (Qt6 branch), all of the rendering of each widget is done in its own FBOs (aka: off-screen buffers), as opposed to the old Qt5/QGLWidget branch where the rendering was done in each GGLWidget's backbuffer (aka: GL_BACK, an on-screen framebuffer surface).
With QOpenGLWidget, it is now the WainWindow's …

Feature/Qt6 - Fix error popup occurs when opening presentation device (eg: NDI)

---

rvcmds.sh

Fixes #712 
Thanks to Open RV community member [herronelou](https://github.com/herronelou) who reported this issue (#712).
herronelou found out that the latest MSYS2 install:
<<
In recent versions of MSYS2, $OSTYPE is now reporting cygwin, not msys, causing an issue at https://github.com/AcademySoftwareFoundation/OpenRV/blob/main/rvcmds.sh#L35
See their announcement: https://www.msys2.org/news/
>> 
Thank you [herronelou](https://github.com/herronelou)!
In this commit, the rvcmds.sh script was adapted to support both the older MSYS2 (reporting $OSTYPE as msys), and the newer MSYS2 (reporting $OSTYPE as cygwin).
Successfully tested on Windows using both an older MSYS2 install and the latest MSYS2 install (msys2-x86_64-20250221.exe) containing the MSYS2 change.

712: Adapt build to latest MSYS2 release

---

src/bin/apps/rv/CMakeLists.txt
src/bin/apps/rv/main.cpp
src/lib/app/RvCommon/CMakeLists.txt
src/lib/app/RvCommon/RvWebManager.cpp
src/lib/mu/MuQt5/RvNetworkAccessManager.cpp
src/lib/mu/MuQt6/RvNetworkAccessManager.cpp

n/a
I have eliminated all instances of QTextCodec, as this class is no longer supported in Qt 6. Previously, the code relied on the Core5Compat library, which incorporates deprecated and obsolete Qt 5 classes.
I created a python plugin to execute the httpGet method from the RvWebManager class.

Feature/qt6 - Remove usage of Core5Compat library

---

src/lib/mu/MuQt6/QTextStreamType.cpp
src/lib/mu/MuQt6/handrolled/QTextStreamSymbols.cpp
src/plugins/rv-packages/rvnuke/rvNetwork.py
src/plugins/rv-packages/rvnuke/rvnuke_mode.mu.in

n/a
This PR update the rvNetwork,py to Python 3 (copied from src/plugins/python/network/network/rvNetwork.py) and fix some issues in the Mu binding for the QTextStream class.
I will also update the rvNetwork.py file in the main branch in another PR.
Nuke and RV integration was broken. An image or video could not be played in RV.
Rocky Linux 8

Feature/Qt6 - Fix nuke and rv integration

---

src/lib/app/RvCommon/RvApplication.cpp

This fixes SG-36654 SG-36655 SG-36656 
Added a method to filter out some Qt messages that are known/harmless warnings.
One such warning had Qt reporting a warning about a scroll event occuring from a HID device whenever it was connected/disconnected/kvm'd.   This appears to be fixed with Qt 6.6.3 but we are at 6.5.3, so we shut it up.
Another such warning was about a Qt handler for a type conversion already registered (but when initializing PyQt it was tried to be initialized again), etc.
Pollutes the console window needlessly with harmless warnings which are Qt bugs that were later fixed.
macOS and Linux.

Feature/Qt6 - Fix various qt console warnings

---

src/lib/app/RvCommon/RvApplication.cpp
src/lib/audio/QTAudioRenderer/QT5AudioRenderer.cpp
src/lib/audio/QTAudioRenderer/QTAudioRenderer.cpp
src/lib/audio/QTAudioRenderer/QTAudioRenderer/QTAudioRenderer.h

n/a
Removed #ifdef related to RV_VFX_CY2023 since they are not needed in QTAudioRenderer class (QT5AudioRenderer is used for CY2023).
Clean up code to make it more readable.
Rocky Linux 8

Feature/qt6 - Clean up code in QTAudioRenderer class

---

cmake/dependencies/ffmpeg.cmake
src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp

n/a
Adding PNG codec to the slow random access array and changing the seeking offset to -1 instead of -3 because RV was using that an offset of -1 before FFmpeg 6.
There are some issues when RV is using two readers threads and FFmpeg multithreading. By adding PNG as a slow random access codec, the decoding performance is a lot better.
Rocky Linux 8
An offset of -1 during seeking had better performance during my testing.

Add PNG as slow random access codec

---

cmake/dependencies/python3.cmake
src/plugins/rv-packages/otio_reader/annotation_hook.py

The `visible` layer attribute is not used anymore to indicate if annotations should be shown or not. Therefore, the `show` attribute of the RVPaint node should not be set with that attribute value. Show and hide annotation actions are now only being handled in the Live Review plugin. The required changes were made in this [PR](https://git.autodesk.com/media-and-entertainment/rv/pull/336).
Since Creative Review is now sending an event as part of the `PLAYBACK_SETTINGS` command, we should not use the `visible` attribute of the OTIO Timeline to know if the annotations should be shown or not.
This change was tested on macOS in a Live Review session between RV and the Creative Review prototype.

Remove show property from annotation hook

---

docs/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-sixteen.md

The following properties were added to the documentation:
-  _order_
- _redo_
- _composite.inputBlendModes_
- _composite.inputOpacities_
- _composite.inputAngularMaskActive_
- _composite.inputAngularMaskPivotX_
- _composite.inputAngularMaskPivotY_
- _composite.inputAngularMaskAngleInRadians_
- _composite.swapAngularMaskInputs_
Some formatting was also done to address markdownlint warnings.
_order_, _redo_ and _composite.inputBlendModes_ were added to the documentation a while ago, but were never added to the _Node Reference_ documentation page. The other properties are new additions to handle the Compare mode in Live Review.
The change was tested on MacOS.

SG-36871: Add missing RVNode properties to documentation

---

README.md

Add detailed instructions on how to enable clang-tidy to lint the C++ code of the project.
A .clang-tidy file was added in this [PR](https://github.com/AcademySoftwareFoundation/OpenRV/pull/648), but README.md was not updated to highlight the addition of that file to the project.
After following the steps mentioned in README.md, you should now see warnings from clang-tidy in your IDE. This is what it should look like in VSCode:

SG-38658: Add clang-tidy instructions in README.md

---

src/plugins/rv-packages/annotate/annotate_mode.mu

The keywords start and end were added as delimiters for a list of strokes cleared on the same frame in _clearPaint_. If the keywords are detected in _redoPaint_ all the strokes between the two words will be added to the undo stack and removed from the redo stack. Otherwise, only one stroke is added. Note that the keywords are not added to the undo stack since each stroke should be popped individually once that action is reached.
The current undo/redo implementation in the annotation tool needed to be updated to match the annotation behaviour in the Live Review plugin.
The changes were tested on macOS.
https://github.com/user-attachments/assets/dd8a1c4f-4667-486d-8c57-53a3a6cafce7

SG-38731: Update annotation tool's undo/redo and clear to match Live Review's behaviour

---

src/lib/ip/OCIONodes/OCIOIPNode.cpp

Fixes #746 
Removed the pass-through logic when the gpuProcessor->isNoOp() is true as it was causing issues when using annotations in stack mode and a raw display/view was selected.

746: fix issue with with new OCIOIPNode optimisations and viewing in stack mode.

---

.github/workflows/ci.yml

n/a
The old caches systems used by Github Actions were [decommissioned on the 15th of April](https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/) and that causes issue with AQT (Qt installer). Therefore, the  Qt packages are always downloaded currently, and it seems like there are issues with some modules downloaded from mirrors (e.g. checksum calculation).
I will try to update to the latest version of AQT and see if something was done. Otherwise, I might have to do something like this:
https://github.com/dpaulat/supercell-wx/commit/d34224c1351527097d5d24954906cf953769937d
Fix the CI

Fix issue with CI - related to AQT

---

.github/workflows/ci.yml
src/lib/audio/QTAudioRenderer/QTAudioRenderer.cpp
src/lib/audio/QTAudioRenderer/QTAudioRenderer/QTAudioRenderer.h

n/a
I removed the conditions to check the state of the QAudioSink object because it does not make sense in Qt 6. In Qt 6, when we call the `start `method on the QAudioSink object, The code starts transferring audio data from the device to the system's audio output right away and changes the device state afterwards (while in Qt 5, the state was changed first, and then the audio data was read). Therefore, it does not make sense to check the state in the `readData` callback because even if the state is STOPPED, we want to start reading the audio data.
The audio cache/processing seems to behave just like the main branch with those changes. I tested it on Windows and MacOS.
Fix audio on Windows and the new logic makes more sense based on how Qt 6 works now.
Windows and MacOS

Feature/Qt6 - Small tweak of the audio logic

---

src/lib/app/RvCommon/QTTranslator.cpp
src/lib/app/TwkApp/TwkApp/Event.h
src/plugins/rv-packages/annotate/annotate_mode.mu

NA
@cedrik-fuoco-adsk had already did the bulk of the work to port the QTTranslator from Qt5 to Qt6 but the QTabletEvent needed some attention because of the Qt6 refactoring with respect to its events handling.
**TabletDevice and TabletKind were removed**
Rationale:
In RV, when handling a table event, we used to record the TabletDevice (ie stylus) and the TabletKind (ie pen or eraser) in the RV's TableEvent class.
In Qt6, QTabletEvent::FourDMouse and QTabletEvent::RotationStylus have been removed and replaced with QInputDevice::DeviceType::Puck and QInputDevice::DeviceType::Stylus respectively. 
So technically we would have had to create Qt version specific enums of TabletDevice and TabletKind.
However, they were NOT used anywhere. Note that the important part is the name of the event …

Finalize port of QTabletEvent to Qt6 and fix tablet eraser issue

---

CMakeLists.txt

n/a
Bump OpenRV to version 3.
Since feature/qt6 is now merged into main, let's bump OpenRV version to 3.

Bump to OpenRV 3

---

src/lib/app/RvCommon/RvCommon/RvTopViewToolBar.h
src/lib/app/RvCommon/RvPreferences.cpp
src/lib/app/RvCommon/RvTopViewToolBar.cpp

Hardware Stereo Shutter mode gone since Qt6/QOpenGLWidget. 
(eg: nvidia glasses circa 2011)
There is apparently no customer demand for it, and review of stereo footage is apparently done using other methods regardless. We're leaving existing code in case customers want to revive it.
Tested on macOS,  simply commented out the few lines of code required to make this option available in the UI. Most of the code to enable the feature is found in DisplayStereoIPNode, which we have not touched.
n/a

Qt6: Disable stereo shutter glass support 

---

src/lib/app/mu_rvui/extra_commands.mu

Fixes #38915, a small regression I introduced. where getStringProperty() may throw an exception if the property does not exist. That particular small change in my other PR was actually not quite needed anyway, since we changed the ui name dupe check algorithm which went from O(n^2-or-3) to O(n log(n)).
This was a regression in the automated tests. I just added the old code back.
macOS. I just added back the old mu code.

Fix regression because getStringProperty(name) may throw exception

---

cmake/dependencies/boost.cmake
cmake/dependencies/png.cmake
cmake/dependencies/zlib.cmake
docs/build_system/config_macos.md
rvcmds.sh
src/build/make_openssl.py
src/build/make_pyside6.py
src/lib/base/TwkMath/TwkMath/Mat33.h
src/lib/base/TwkMath/TwkMath/Plane.h
src/lib/mu/Mu/Mu/config.h

NA
The Open RV build got broken with the latest macOS Sequoia 15.5 + Xcode 16.3-clang17 + latest Homebrew.
This commit fixes these errors and also update the Open RV build instructions on macOS.
Note that this commit is not enough to successfully build Open RV with the latest macOS.
It is missing one template error which has been fixed in a separate repo and will be added to this PR once it is merged merged:
https://github.com/shotgunsoftware/openrv-pub/pull/21
This commit fixes numerous legacy template errors that were not reported as such by previous versions of clang.
This commit also contains some changes in the Open RV build instructions on macOS in order to achieve a successful Open RV build on the latest macOS configuration. 
- Updated PNG from 16.39.0 to 16.48.0 to fix the …

Fix build when using latest Xcode 16.3-clang 17

---

src/build/make_pyside6.py
src/build/utils.py

NA
Fix a build break with the macOS build of Open RV when using the very latest version of Xcode/clang released a couple of days ago.
This commit fixes an issue with the very latest version of Xcode/clang where the clang binary matching the new version is not available on the Qt mirror site. This commit adds a fall back mechanism so that a known version of clang can be used if the specific clang version binary matching the Xcode/clang is not available from the Qt mirror site.
Successfully tested on macOS using the latest version of Xcode/clang : clang 17.0.13 which doesn't have a matching binary on the Qt mirror site.

Add fallback version when clang download fails

---

src/plugins/rv-packages/stereo_disassembly/PACKAGE
src/plugins/rv-packages/stereo_disassembly/stereo_disassembly_help.asciidoc
src/plugins/rv-packages/stereo_disassembly/stereo_disassembly_help.html

While scanning the packages, I came across this type and did a code base scan of the instances of this typo and updated the affected files.
To make it clearer to search for the associated files related to this package
Windows 11 build from latest main branch
`src/plugins/rv-packages/stereo_disassembly/PACKAGE` : 1,51
`src/plugins/rv-packages/stereo_disassembly/stereo_disassembly_help.asciidoc` : 28
`src/plugins/rv-packages/stereo_disassembly/stereo_disassembly_help.html` : 615

Fix typo in Stereo Disassembly rv package name changed from "Stereo Disassmbly"

---

docs/build_system/config_macos.md

Add the steps to set up VSCode on macOS to debug RV's C++ code.
At the last Open RV TSC meeting, someone ask if some instructions could be added to the macOS documentation to set up the C++ debugger in VSCode.

Add VSCode debugging documentation for macOS

---

cmake/dependencies/patch/pyopengl-accelerate.patch
cmake/dependencies/python3.cmake
src/build/requirements.txt

NA
To fix build break on mac intel: PyOpenGL-accelerate
This is a cherry pick from a fix from the OpenRV main branch.
For reference: https://github.com/AcademySoftwareFoundation/OpenRV/commit/36a92db3a5f2f863a247b568bb594d2df25ae443
Successfully testes on mac intel

Fix issue with PyOpenGL-accelerate on MacOS x86_64

---

src/lib/app/RvCommon/RvBottomViewToolBar.cpp
src/lib/ip/IPCore/IPGraph.cpp

Note that this is a cherry pick from the RB-2.2.0-VFX2023 branch.
NA
I have identified two problematic behaviours with the Mute Audio functionality in RV:
**Problematic Behaviour#1:** 
When clearing an RV session, the RV audio is automatically unmuted. It should not.
**Problematic Behaviour#2:** 
When programmatically muting the RV audio, the RV audio is automatically unmuted the first time you access the RV audio UI without even changing anything. It should not.
**Problematic Behaviour#1:**
In IPGraph::reset(): 
Preserve the mute audio state that we had before the reset. Note that IPGraph::reset() is called when clearing an RV session
**Problematic Behaviour#2:** 
In RvBottomViewToolBar::audioSliderChanged():
The idea is to unmute the RV audio whenever someone changes the RV audio …

Fix 2x mute audio issues (#791)

---

src/build/make_pyside.py
src/build/make_pyside6.py
src/build/make_python.py

n/a
Added the build type as parameter for `get_python_interpreter_args` to make sure that the right Python is returned. The change has no effect on other platform because the other platforms does not have a debug prefix for Python Debug.
Currently, the Python Release executable is **always** used in Windows Debug to install `numpy` and that causes issue with Nanobind since Nanobind is using Python Debug. The issue has been there for a long time
Windows

Windows - Make sure the right Python is used in Windows Debug

---

src/plugins/output/BlackMagicDevices/DeckLinkVideoDevice.cpp

Add 120Hz SDI format support to the BMD SDI path for 1080p, DCI 2K, UHD 4K, and DCI 4K. Note that the formats were added at the end of the list to follow #652 comment about user preferences based on format indexes.
These missing formats were supported by the Blackmagic DeckLink SDK but had never beed added to RV until today.
The video formats were added based on the DeckLink SDK documentation. However, since we don't have access to the monitor needed to test them, no tests were performed.

SG-39413: Add BMD SDI support for 120Hz

---

src/lib/app/ImGuiPythonBridge/ImGuiPythonBridge.cpp
src/lib/app/ImGuiPythonBridge/ImGuiPythonBridge.h
src/lib/app/RvCommon/DiagnosticsView.cpp
src/lib/app/RvCommon/RvCommon/DiagnosticsView.h

When no python plugin registers diagnostics callbacks, and the callback window is open, show an ImGui window with instructions on how to make your first diagnostics info panel
An empty diagnostics window is really boring and pointless and full of question marks from users.
macOS.

Added sample window if diagnostics are empty

---

src/bin/apps/rv/main.cpp
src/bin/nsapps/RV/main.cpp
src/lib/app/RvCommon/GLView.cpp
src/lib/app/RvCommon/MuUICommands.cpp
src/lib/app/RvCommon/QTGLVideoDevice.cpp
src/lib/app/RvCommon/RvCommon/GLView.h
src/lib/app/RvCommon/RvCommon/MuUICommands.h
src/lib/app/RvCommon/RvCommon/QTGLVideoDevice.h
src/lib/app/TwkApp/TwkApp/VideoDevice.h
src/lib/app/mu_rvui/HUD.mu
src/lib/app/mu_rvui/commands.mud
src/lib/app/mu_rvui/glyph.mu
src/lib/app/mu_rvui/inspector.mu
src/lib/app/mu_rvui/motion_scope.mu
src/lib/app/mu_rvui/rvtypes.mu
src/lib/app/mu_rvui/rvui.mu
src/lib/app/mu_rvui/timeline.mu
src/lib/app/mu_rvui/wipes.mu
src/lib/app/py_rvui/rv_commands_setup.py
src/lib/ip/IPMu/CommandsModule.cpp
src/plugins/rv-packages/annotate/annotate_mode.mu

NA
Taking advantage of high DPI monitor capabilities for nicer RV UI and better media resolution.
This PR is leveraging Qt's high DPI capability in RV:
https://doc.qt.io/qt-6/highdpi.html
It is pretty straightforward: a high DPI scaling factor is available on a per screen basis via the QScreen::devicePixelRatio().
On non high DPI monitors or display resolution, this devicePixelRatio is 1.0f.
On high DPI monitors and compatible resolutions, QScreen::devicePixelRatio() returns a high DPI scaling factor that needs to be applied both in X and Y.
Note that this is on a per screen basis because a computer system could have multiple monitors of various high DPI capabilities and resolutions.
In this commit, the float GLView::devicePixelRatio() method was added which effectively returns the …

Add High DPI Display support to RV

---

src/lib/app/ImGuiPythonBridge/ImGuiPythonBridge.cpp
src/lib/app/ImGuiPythonBridge/ImGuiPythonBridge.h

Fixes SG-39680
I silenced the reference decrement in the python object deleter; I'll have to wait for Cedrik to create a proper fix for this. 
Ideally we want to call clearCallbacks() before exiting the app, there seems to be a weird race condition that prevents us from doing so. 
Furthermore, decrementing the refcount in the deleter appears to run counter to the fact that we're already decrementing the refcount when we unregister the callback.  I'm not sure if we're meant to keep the refcount derement in the deleter, or even if the deleter is needed at all at this point. 
Segfault on exit, need to send beta build.
macOS
Make sure we don't sefault on exit
n/a

SG-39680: Fixed crash on exit with registered imgui callback (temp patch)

---

docs/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-five.md
docs/rv-manuals/rv-reference-manual/rv-reference-manual-chapter-sixteen.md
src/bin/imgtools/rvio/main.cpp
src/lib/app/RvApp/RvApp/RvSession.h
src/lib/app/RvApp/RvSession.cpp
src/lib/app/RvCommon/RvBottomViewToolBar.cpp
src/lib/app/mu_rvui/mode_manager.mu
src/lib/ip/IPBaseNodes/IPBaseNodes/PaintIPNode.h
src/lib/ip/IPBaseNodes/PaintIPNode.cpp
src/lib/ip/IPCore/Session.cpp
src/lib/ip/IPCore/SessionIPNode.cpp
src/plugins/rv-packages/annotate/PACKAGE
src/plugins/rv-packages/annotate/annotate_mode.mu
src/plugins/rv-packages/otio_reader/annotation_hook.py

The Hold and Ghost properties were moved from the PaintIPNode to the SessionIPNode. Instead of being applied to each strokes and text boxes, they are now considered as global properties since all strokes and text boxes of all paint nodes should have the same Hold and Ghost values. The behaviour of the Paint node is pretty much the same expect for the fact that it uses the values from the Session node instead of stocking a value per stroke. The documentation was updated to reflect that change. The Annotation mode package was reverted to its previous behaviour since having the properties applied to the whole session means that mode doesn't need to be active for the properties to be updated and for the annotations to be rendered properly. The Annotation hook used for an OTIO-based Live …

SG-39476: Refactor Hold and Ghost as session wide properties

---

src/lib/app/mu_rvui/rvui.mu

Fixes https://github.com/AcademySoftwareFoundation/OpenRV/issues/828
Removes the Q shortcut to close Open RV. Ctrl-Q still enabled.

828: Remove Q shortcut from rvui.mu

---

src/lib/app/RvApp/CommandsModule.cpp
src/lib/ip/IPBaseNodes/IPBaseNodes/FileSourceIPNode.h

NA
This commit fixes a potential imbalance between before-progressive-loading and after-progressive-loading events when progressive source loading is active.
This commit only affects Open RV when the progressive source loading is enabled 
Which can be done via by setting the following env var:
export RV_PROGRESSIVE_SOURCE_LOADING=1
Also in this commit :  properly initialized a progressive source loading variable m_loadingID which was uninitialized.
This event imbalance proved to be detrimental to a recent mechanism that was introduced in RV Live Review where some commands such as addSourceVerbose() or clearSession() for examples, are executed on the participant RVs as native commands instead of broadcasting the numerous RV graph changes which are a side effect of such meta command. …

Fix before/after-progressive-loading events imbalance

---

src/plugins/rv-packages/annotate/annotate_mode.mu

When joining a Live Review session, the Annotation panel should be closed if it was still open. Since a participant shouldn't be allowed to annotate the media in a standard Live Review session, there is no reason for the panel to be available.
In a previous PR, options and menus related to annotations were blocked for participants of a Live Review session. However, if the Annotation panel was opened when joining a session, it would stay that way. This can be confusing to the participant since all other options are disabled. 
Testing joining a Live Review session with the Annotation panel opened and closed was perform on macOS

SG-39510: Close annotation panel when joining Live Review

---

src/lib/app/mu_rvui/mode_manager.mu

Block annotate_mode and session_manager when an event triggers toggling their panel.
Blocking the modes inside the `bind` function wasn't blocking the Annotation Panel hotkey when the Live Review Panel was focused on since this path was not used in that case. Moving the validation inside `toggleEntryMode` fixed the issue. Only the Annotation Panel was affected by this issue since it's the only one that is only displayed on the right panel, just like the Live Review panel.
Clicking the F10 key while the Live Review Panel is focused on was tested on macOS.

SG-39876: Block Annotation Panel in Live Review

---

src/lib/app/mu_rvui/rvui.mu

Block the Zoom and Pan hotkeys if RV is a participant of a Live Review session.
Multiple menus and options are now disabled or blocked when RV is a participant of a Live Review session. However, it was still possible for a user to enable Zoom and Pan through their hotkeys. As a participant, RV should only be a viewer and display exactly what's on the presenter's screen.
Zoom and Pan outside and inside a Live Review session was tested on macOS.
https://github.com/user-attachments/assets/c5004e74-f102-4edd-8c1d-f6adf7469bd0

SG-39832: Block Zoom and Pan to participants of Live Review

---

cmake/dependencies/imgui/CMakeLists_PyImGUI.cmake
cmake/dependencies/imgui/CMakeLists_PyImplot.cmake
cmake/dependencies/pyimgui.cmake
cmake/dependencies/pyimplot.cmake

n/a
PyImGUI and PyImPlot could not be imported on Windows.
Make sure that the pyd module is generated and copy it to the right location.
Windows

Fix issue when importing pyimgui and pyimplot in a Python plugin on Windows

---

src/build/make_pyside6.py
src/lib/app/ImGuiPythonBridge/ImGuiPythonBridge.cpp
src/lib/app/RvCommon/DiagnosticsView.cpp
src/lib/app/RvCommon/RvCommon/DiagnosticsView.h
src/lib/app/RvCommon/RvDocument.cpp

n/a
The primary issue was an always-on 25fps timer that consumed CPU/GPU resources even when the diagnostics window was never opened, along with eager initialization of ImGui/ImPlot contexts and Python bridge overhead. 
The solution was to implemented a lazy initialization where all expensive operations (ImGui context creation, timer connections, Python bridge setup) are deferred until the diagnostics window is first shown.
Additionally, I improved the shutdown sequence to prevent the application from hanging and crashing during exit.
Finally, I removed duplicated code in DiagnosticsView that was not used.
- Segmentation fault when leaving the application because the code was trying to delete Python references that did not exist anymore
- Slowness and High CPU usage seen during …

Refactor diagnostics view

---

src/lib/app/mu_rvui/commands.mud
src/lib/app/py_rvui/rv_commands_setup.py
src/lib/ip/IPMu/CommandsModule.cpp

Add refreshOutputVideoDevice in CommandsModule.cpp and rv_commands_setup.py to access the function in Python.
When loading a media file, RV calls systematically `setOutputVideoDevice` in `readGTO` of RVSession.cpp. However, when joining an OTIO-based Live Review session, this path is never used and the output video device will not be set properly after quitting and joining back a session. To replicate the normal behaviour the output video device should be set when joining an OTIO-based Live Review session. To do so, that C++ function needs to be available in Python through the commands module. Note that this behaviour was not affecting RV to RV Live Review session since in that case, `readGTO` was being called.
Quitting and joining back an OTIO-based Live Review session with the …

SG-39830: Add refreshOutputVideoDevice to CommandsModule

---

src/lib/ip/IPBaseNodes/PaintIPNode.cpp

Change fallback values of duration and startFrame when the properties are not defined on the paint node. For duration, that value should have been 1 instead of 0. For startFrame, the frame value is access through the pen component that is format as follows: `"pen:strokeId:frameNumber:user"`. Even if it wasn't causing an issue, I changed the `ghostBefore` and `ghostAfter` values to 5 instead of 0 to match what the SessionIPNode is setting since 0 doesn't make sense here.
The `duration` and `startFrame` properties were added to know when and for how long to display held and ghosted annotations as well as calculate the opacity level for ghosted annotations. However, these two properties doesn't exist in previous version of RV. This is causing an issue, because annotations saved in an older …

SG-39984: Fix duration and startFrame paint properties

---

src/bin/imgtools/rvio/UICommands.cpp
src/bin/imgtools/rvio/UICommands.h

NA
rvio has its own set of stub UI commands which are effectively noop to make sure it can loads other scripts with UI command. The devicePixelRatio() UI command was recently introduced but I omitted to add an associated stub command to rvio. My bad.
rvio was complaining about the missing devicePixelRatio() command:
RV.app/Contents/PlugIns/Mu/rvtypes.mu, line 530, char 49: Unresolved function call to "devicePixelRatio"
ERROR: while loading source module "/RV.app/Contents/PlugIns/Mu/rvtypes.mu"
ERROR: attempted call to unresolved function
RV.app/Contents/PlugIns/Mu/glyph.mu, line 527, char 43: Unresolved function call to "devicePixelRatio"
ERROR: while loading source module "RV.app/Contents/PlugIns/Mu/[glyph.mu](http://glyph.mu/)"
Successfully tested on macOS

Fix missing devicePixelRatio() ui stub cmd for rvio

---

src/bin/apps/rv/main.cpp

NA
- Disable High DPI support by default on Windows.
- On Windows, restore the "RV_QT_HDPI_SUPPORT" environment variable to be able to re-enable it (it was also used in previous versions of RV.)
This is a temporary measure due to reported crashes with QtWebEngineWidgets in Qt 6.5.3 on high DPI displays on Windows.

Disable High-DPI by Default on Windows

---

cmake/dependencies/ocio.cmake
src/lib/app/mu_rvui/CMakeLists.txt
src/lib/mu/MuQt6/QGuiApplicationType.cpp
src/lib/mu/MuQt6/QScreenType.cpp
src/lib/mu/MuQt6/QWidgetType.cpp

Fixes #885
**Problem:**
RV was sometimes crashing when fitting the window to image - w keyboard shortcut
**Cause:**
The source of this isssue is that the FitWindowToImage functionality uses a new Qt6 functionality: QGuiApplication::screenAt() wrapped in the Mu command qt.QGuiApplication.screenAt().
Now this new Qt6 method can possibly returns nullptr if the position nis outside any visible screen.
The new associated Mu binding was always wrapping the returned pointer as a Mu object no matter what: makeinstance<QScreenType>.
Which is why the crash occurred: when the position was outside the screen then the Mu code would reference the nullptr.
**Solution:**
Now returning a nullptr for all Mu bindings wrapping a QScreen as a Mu object: makeinstance<QScreenType>
I did that for all the places …

Fix fit window to image crash - w keyboard shortcut

---

src/lib/app/mu_rvui/glyph.mu

Fixes #889
Could not add new content sources via drag and drop when a source is already loaded on High-DPI displays
Now taking devicePixelRatio (High-DPI display) into account in drawDropRegions() mu method.
Successfully tested on macOS

Fix drop region for High-DPI displays (#889)

---

cmake/dependencies/patch/imgui_cpp_h.patch

n/a
Allow ImGui to use more vertex indices
Live review diagnostics was hitting the maximum number of vertex indices.

Allow imgui to use more vextex indices

---

src/lib/image/MovieFFMpeg/MovieFFMpeg.cpp
src/lib/image/MovieFFMpeg/MovieFFMpeg/MovieFFMpeg.h

n/a
When the streams metadata do not have the timecode information, I added a fallback mechanism that looks at the format context metadata and try to find the `timecode` information.
During testing, there were some MXF media files that had the wrong start time.
MacOS

Add fallback to search for timecode in FFmpeg format context metadata

---

src/plugins/rv-packages/annotate/annotate_mode.mu

Replace QColorDialog `currentColorChanged` signal with `colorSelected`.
`currentColorChanged` is a signal emitted whenever the color is changed in the dialog. This means that "Ok" and "Cancel" had no effect since the color was already changed as soon as it was selected. `colorSelected` is emitted just after "Ok" is clicked to set the color to use. That way, the color is only set after the user has clicked on "Ok", quitting the dialog or clicking on "Cancel" will not save the selected color.
Selecting colors through the QColorDialog was tested on macOS.

SG-39966: Fix annotation color selection

---

src/build/requirements.txt

This pins the OTIO python module to a specific commit since the latest commit doesn't work with the compiled python interpreter.

Pin OpenTimelineIO to specific commit in python build

---

.git-blame-ignore-revs
.github/workflows/ci.yml
.pre-commit-config.yaml
docs/build_system/config_common_build.md
ruff.toml

Note that multiple files had too many issues that would need to manually be reviewed to follow best practices and pass Ruff linting rules. The idea here was not to fix everything but rather to add tools to make working on this project easier. For that reason, some rules were ignore in specific files in `ruff.toml` that is added in another PR. Since some of these files were added recently, we should to take the time to fix them properly and make sure the code is following Python's conventions.
This PR adds a `Lint and Format` step in our Github actions CI and Ruff as a `pre-commit` hook to lint and format our Python code. I also added some documentation on how to use these tool to contribute to the project when working on Python files.
The files to review are:
- …

Add Ruff linter and formatter
